using BOSLib;
using System;
namespace BOSERP
{
    #region ACDocumentEntrys
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ACDocumentEntrysInfo
    //Created Date:Tuesday, June 28, 2011
    //-----------------------------------------------------------

    public class ACDocumentEntrysInfo : BusinessObject
    {
        public ACDocumentEntrysInfo()
        {
            ACDocumentDate = DateTime.MaxValue;
        }

        #region Variables
        protected int _aCDocumentEntryID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ACDocumentID;
        protected int _fK_ACObjectID;
        protected int _fK_ACAssObjectID;
        protected int _fK_ACCostObjectID;
        protected int _fK_ACEntryTypeID;
        protected int _fK_ACDebitAccountID;
        protected int _fK_ACCreditAccountID;
        protected int _fK_BRCostedBranchID;
        protected String _aCDocumentEntryDesc = String.Empty;
        protected decimal _aCDocumentEntryAmount;
        protected decimal _aCDocumentEntryExchangeAmount;
        protected decimal _aCDocumentEntryAllocatedAmount;
        protected String _aCObjectType = String.Empty;
        protected String _aCAssObjectType = String.Empty;
        protected int _aCAssetID;
        protected decimal _aCAssetDepreciatedQty;
        protected int _iCEquipmentShipmentItemID;
        protected int _aCEquipmentTransferItemID;
        protected decimal _iCEquipmentDepreciatedQty;
        protected int _aCAllocatedDocumentEntryID;
        protected int _fK_ACUnfinishedConstructionCostID;
        protected int _fK_ACCostCenterID;
        protected int _fK_ACSegmentID;
        protected int _fK_HRDepartmentID;
        protected int _fK_ICProductIdentifiedEquipmentID;
        protected int _fK_PMProjectID;
        protected int _fK_BRBranchID;
        protected int _fK_VMVehicleID;
        #endregion

        #region Public properties
        public int ACDocumentEntryID
        {
            get { return _aCDocumentEntryID; }
            set
            {
                if (value != this._aCDocumentEntryID)
                {
                    _aCDocumentEntryID = value;
                    NotifyChanged("ACDocumentEntryID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_ACDocumentID
        {
            get { return _fK_ACDocumentID; }
            set
            {
                if (value != this._fK_ACDocumentID)
                {
                    _fK_ACDocumentID = value;
                    NotifyChanged("FK_ACDocumentID");
                }
            }
        }
        public int FK_ACObjectID
        {
            get { return _fK_ACObjectID; }
            set
            {
                if (value != this._fK_ACObjectID)
                {
                    _fK_ACObjectID = value;
                    NotifyChanged("FK_ACObjectID");
                }
            }
        }
        public int FK_ACAssObjectID
        {
            get { return _fK_ACAssObjectID; }
            set
            {
                if (value != this._fK_ACAssObjectID)
                {
                    _fK_ACAssObjectID = value;
                    NotifyChanged("FK_ACAssObjectID");
                }
            }
        }
        public int FK_ACCostObjectID
        {
            get { return _fK_ACCostObjectID; }
            set
            {
                if (value != this._fK_ACCostObjectID)
                {
                    _fK_ACCostObjectID = value;
                    NotifyChanged("FK_ACCostObjectID");
                }
            }
        }
        public int FK_ACEntryTypeID
        {
            get { return _fK_ACEntryTypeID; }
            set
            {
                if (value != this._fK_ACEntryTypeID)
                {
                    _fK_ACEntryTypeID = value;
                    NotifyChanged("FK_ACEntryTypeID");
                }
            }
        }
        public int FK_ACDebitAccountID
        {
            get { return _fK_ACDebitAccountID; }
            set
            {
                if (value != this._fK_ACDebitAccountID)
                {
                    _fK_ACDebitAccountID = value;
                    NotifyChanged("FK_ACDebitAccountID");
                }
            }
        }
        public int FK_ACCreditAccountID
        {
            get { return _fK_ACCreditAccountID; }
            set
            {
                if (value != this._fK_ACCreditAccountID)
                {
                    _fK_ACCreditAccountID = value;
                    NotifyChanged("FK_ACCreditAccountID");
                }
            }
        }
        public int FK_BRCostedBranchID
        {
            get { return _fK_BRCostedBranchID; }
            set
            {
                if (value != this._fK_BRCostedBranchID)
                {
                    _fK_BRCostedBranchID = value;
                    NotifyChanged("FK_BRCostedBranchID");
                }
            }
        }
        public String ACDocumentEntryDesc
        {
            get { return _aCDocumentEntryDesc; }
            set
            {
                if (value != this._aCDocumentEntryDesc)
                {
                    _aCDocumentEntryDesc = value;
                    NotifyChanged("ACDocumentEntryDesc");
                }
            }
        }
        public decimal ACDocumentEntryAmount
        {
            get { return _aCDocumentEntryAmount; }
            set
            {
                if (value != this._aCDocumentEntryAmount)
                {
                    _aCDocumentEntryAmount = value;
                    NotifyChanged("ACDocumentEntryAmount");
                }
            }
        }
        public decimal ACDocumentEntryExchangeAmount
        {
            get { return _aCDocumentEntryExchangeAmount; }
            set
            {
                if (value != this._aCDocumentEntryExchangeAmount)
                {
                    _aCDocumentEntryExchangeAmount = value;
                    NotifyChanged("ACDocumentEntryExchangeAmount");
                }
            }
        }
        public decimal ACDocumentEntryAllocatedAmount
        {
            get { return _aCDocumentEntryAllocatedAmount; }
            set
            {
                if (value != this._aCDocumentEntryAllocatedAmount)
                {
                    _aCDocumentEntryAllocatedAmount = value;
                    NotifyChanged("ACDocumentEntryAllocatedAmount");
                }
            }
        }
        public String ACObjectType
        {
            get { return _aCObjectType; }
            set
            {
                if (value != this._aCObjectType)
                {
                    _aCObjectType = value;
                    NotifyChanged("ACObjectType");
                }
            }
        }
        public String ACAssObjectType
        {
            get { return _aCAssObjectType; }
            set
            {
                if (value != this._aCAssObjectType)
                {
                    _aCAssObjectType = value;
                    NotifyChanged("ACAssObjectType");
                }
            }
        }
        public int ACAssetID
        {
            get { return _aCAssetID; }
            set
            {
                if (value != this._aCAssetID)
                {
                    _aCAssetID = value;
                    NotifyChanged("ACAssetID");
                }
            }
        }
        public decimal ACAssetDepreciatedQty
        {
            get { return _aCAssetDepreciatedQty; }
            set
            {
                if (value != this._aCAssetDepreciatedQty)
                {
                    _aCAssetDepreciatedQty = value;
                    NotifyChanged("ACAssetDepreciatedQty");
                }
            }
        }
        public int ICEquipmentShipmentItemID
        {
            get { return _iCEquipmentShipmentItemID; }
            set
            {
                if (value != this._iCEquipmentShipmentItemID)
                {
                    _iCEquipmentShipmentItemID = value;
                    NotifyChanged("ICEquipmentShipmentItemID");
                }
            }
        }
        public int ACEquipmentTransferItemID
        {
            get { return _aCEquipmentTransferItemID; }
            set
            {
                if (value != this._aCEquipmentTransferItemID)
                {
                    _aCEquipmentTransferItemID = value;
                    NotifyChanged("ACEquipmentTransferItemID");
                }
            }
        }
        public decimal ICEquipmentDepreciatedQty
        {
            get { return _iCEquipmentDepreciatedQty; }
            set
            {
                if (value != this._iCEquipmentDepreciatedQty)
                {
                    _iCEquipmentDepreciatedQty = value;
                    NotifyChanged("ICEquipmentDepreciatedQty");
                }
            }
        }
        public int ACAllocatedDocumentEntryID
        {
            get { return _aCAllocatedDocumentEntryID; }
            set
            {
                if (value != this._aCAllocatedDocumentEntryID)
                {
                    _aCAllocatedDocumentEntryID = value;
                    NotifyChanged("ACAllocatedDocumentEntryID");
                }
            }
        }
        public int FK_ACUnfinishedConstructionCostID
        {
            get { return _fK_ACUnfinishedConstructionCostID; }
            set
            {
                if (value != this._fK_ACUnfinishedConstructionCostID)
                {
                    _fK_ACUnfinishedConstructionCostID = value;
                    NotifyChanged("FK_ACUnfinishedConstructionCostID");
                }
            }
        }
        public int FK_ACCostCenterID
        {
            get { return _fK_ACCostCenterID; }
            set
            {
                if (value != this._fK_ACCostCenterID)
                {
                    _fK_ACCostCenterID = value;
                    NotifyChanged("FK_ACCostCenterID");
                }
            }
        }
        public int FK_ACSegmentID
        {
            get { return _fK_ACSegmentID; }
            set
            {
                if (value != this._fK_ACSegmentID)
                {
                    _fK_ACSegmentID = value;
                    NotifyChanged("FK_ACSegmentID");
                }
            }
        }
        public int FK_HRDepartmentID
        {
            get { return _fK_HRDepartmentID; }
            set
            {
                if (value != this._fK_HRDepartmentID)
                {
                    _fK_HRDepartmentID = value;
                    NotifyChanged("FK_HRDepartmentID");
                }
            }
        }
        public int FK_ICProductIdentifiedEquipmentID
        {
            get { return _fK_ICProductIdentifiedEquipmentID; }
            set
            {
                if (value != this._fK_ICProductIdentifiedEquipmentID)
                {
                    _fK_ICProductIdentifiedEquipmentID = value;
                    NotifyChanged("FK_ICProductIdentifiedEquipmentID");
                }
            }
        }
        public int FK_PMProjectID
        {
            get { return _fK_PMProjectID; }
            set
            {
                if (value != this._fK_PMProjectID)
                {
                    _fK_PMProjectID = value;
                    NotifyChanged("FK_PMProjectID");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public int FK_VMVehicleID
        {
            get { return _fK_VMVehicleID; }
            set
            {
                if (value != this._fK_VMVehicleID)
                {
                    _fK_VMVehicleID = value;
                    NotifyChanged("FK_VMVehicleID");
                }
            }
        }
        #endregion


        #region Extra properties
        public String ACAccountName { get; set; }

        public String ACEntryTypeName { get; set; }

        /// <summary>
        /// Gets or sets the credit account no
        /// </summary>
        public String ACDocumentCreditAccount { get; set; }

        /// <summary>
        /// Gets or sets the debit account no
        /// </summary>
        public String ACDocumentDebitAccount { get; set; }

        public String ACDocumentEntryAccountNo { get; set; }
        public String ACDocumentEntryAccountName { get; set; }
        public string ACDocumentEntryAccountNoDisplayText { get; set; }
        public String ACDocumentEntryContraAccountNo { get; set; }

        public int FK_ACDocumentTypeID { get; set; }
        public String ACDocumentNo { get; set; }
        public String ACDocumentName { get; set; }
        public String ACDocumentDesc { get; set; }
        public DateTime ACDocumentDate { get; set; }
        public DateTime ACDocumentPostingDate { get; set; }
        public bool IsPosted { get; set; }
        public int FK_GECurrencyID { get; set; }
        public string MonthYearString { get; set; }
        public DateTime MonthYear { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupExchangeRate)]
        public decimal ACDocumentExchangeRate { get; set; }

        public String ACDocumentTypeName { get; set; }
        public string ACDocumentTypeDesc { get; set; }

        public String APSupplierNo { get; set; }
        public String APSupplierName { get; set; }
        public int APSupplierID { get; set; }
        public string GECurrencyNo { get; set; }
        public string GECurrencyName { get; set; }
        public string BRBranchName { get; set; }

        public bool OwingByDebit { get; set; }

        public bool OwingByCredit { get; set; }

        public string DebitAccountPostingRule { get; set; }

        public string CreditAccountPostingRule { get; set; }

        public string ReceiptDocumentNo { get; set; }

        public string ReceiptDocumentDate { get; set; }

        public string PaymentDocumentNo { get; set; }

        public string ShipmentDocumentNo { get; set; }

        public string ShipmentDocumentDate { get; set; }

        public string ShipmentDocumentDesc { get; set; }

        private string _aCObjectNo;
        public string ACObjectNo
        {
            get { return _aCObjectNo; }
            set
            {
                if (value != this._aCObjectNo)
                {
                    _aCObjectNo = value;
                    NotifyChanged("ACObjectNo");
                }
            }
        }

        private string _aCObjectName;
        public string ACObjectName
        {
            get { return _aCObjectName; }
            set
            {
                if (value != this._aCObjectName)
                {
                    _aCObjectName = value;
                    NotifyChanged("ACObjectName");
                }
            }
        }

        public string GroupValue { get; set; }

        public string HRDepartmentRoomNo { get; set; }

        public string HRDepartmentRoomName { get; set; }

        public string HREmployeeName { get; set; }

        public string ICMeasureUnitName { get; set; }

        public int ACDocumentEntrySourceID { get; set; }

        public decimal ICProductQty { get; set; }

        public int FK_HRAdvanceRequestItemID { get; set; }

        public string ACObjectContactAddress { get; set; }

        public string APBillOfLadingNo { get; set; }
        #region Extra report

        public decimal OpenBalanceCreditAmount { get; set; }
        public decimal OpenBalanceCreditExchangeAmount { get; set; }
        public decimal OpenBalanceDebitAmount { get; set; }
        public decimal OpenBalanceDebitExchangeAmount { get; set; }
        public decimal TransactionCreditAccount { get; set; }
        public decimal TransactionCreditExchangeAccount { get; set; }
        public decimal TransactionDebitAccount { get; set; }
        public decimal TransactionDebitExchangeAccount { get; set; }
        public decimal EndCreditAccount { get; set; }
        public decimal EndCreditExchangeAccount { get; set; }
        public decimal EndDebitAccount { get; set; }
        public decimal EndDebitExchangeAccount { get; set; }
        public string CurrencyNo { get; set; }


        public decimal OpenBalanceCreditAmountVND { get; set; }

        public decimal OpenBalanceCreditAmountUSD { get; set; }

        public decimal OpenBalanceCreditAmountVND4USD { get; set; }

        public decimal OpenBalanceCreditAmountEURO { get; set; }

        public decimal OpenBalanceCreditAmountVND4EURO { get; set; }

        public decimal OpenBalanceCreditAmountRMB { get; set; }

        public decimal OpenBalanceCreditAmountVND4RMB { get; set; }

        public decimal OpenBalanceCreditAmountSGD { get; set; }

        public decimal OpenBalanceCreditAmountVND4SGD { get; set; }

        public decimal OpenBalanceCreditAmountGBP { get; set; }

        public decimal OpenBalanceCreditAmountVND4GBP { get; set; }


        public decimal OpenBalanceDebitAmountVND { get; set; }

        public decimal OpenBalanceDebitAmountUSD { get; set; }

        public decimal OpenBalanceDebitAmountVND4USD { get; set; }

        public decimal OpenBalanceDebitAmountEURO { get; set; }

        public decimal OpenBalanceDebitAmountVND4EURO { get; set; }

        public decimal OpenBalanceDebitAmountRMB { get; set; }

        public decimal OpenBalanceDebitAmountVND4RMB { get; set; }

        public decimal OpenBalanceDebitAmountSGD { get; set; }

        public decimal OpenBalanceDebitAmountVND4SGD { get; set; }

        public decimal OpenBalanceDebitAmountGBP { get; set; }

        public decimal OpenBalanceDebitAmountVND4GBP { get; set; }


        public decimal TransactionCreditAccountVND { get; set; }

        public decimal TransactionCreditAccountUSD { get; set; }

        public decimal TransactionCreditAccountVND4USD { get; set; }

        public decimal TransactionCreditAccountEURO { get; set; }

        public decimal TransactionCreditAccountVND4EURO { get; set; }

        public decimal TransactionCreditAccountRMB { get; set; }

        public decimal TransactionCreditAccountVND4RMB { get; set; }

        public decimal TransactionCreditAccountSGD { get; set; }

        public decimal TransactionCreditAccountVND4SGD { get; set; }

        public decimal TransactionCreditAccountGBP { get; set; }

        public decimal TransactionCreditAccountVND4GBP { get; set; }


        public decimal TransactionDebitAccountVND { get; set; }

        public decimal TransactionDebitAccountUSD { get; set; }

        public decimal TransactionDebitAccountVND4USD { get; set; }

        public decimal TransactionDebitAccountEURO { get; set; }

        public decimal TransactionDebitAccountVND4EURO { get; set; }

        public decimal TransactionDebitAccountRMB { get; set; }

        public decimal TransactionDebitAccountVND4RMB { get; set; }

        public decimal TransactionDebitAccountSGD { get; set; }

        public decimal TransactionDebitAccountVND4SGD { get; set; }

        public decimal TransactionDebitAccountGBP { get; set; }

        public decimal TransactionDebitAccountVND4GBP { get; set; }


        public decimal EndCreditAccountVND { get; set; }

        public decimal EndCreditAccountUSD { get; set; }

        public decimal EndCreditAccountVND4USD { get; set; }

        public decimal EndCreditAccountEURO { get; set; }

        public decimal EndCreditAccountVND4EURO { get; set; }

        public decimal EndCreditAccountRMB { get; set; }

        public decimal EndCreditAccountVND4RMB { get; set; }

        public decimal EndCreditAccountSGD { get; set; }

        public decimal EndCreditAccountVND4SGD { get; set; }

        public decimal EndCreditAccountGBP { get; set; }

        public decimal EndCreditAccountVND4GBP { get; set; }


        public decimal EndDebitAccountVND { get; set; }

        public decimal EndDebitAccountUSD { get; set; }

        public decimal EndDebitAccountVND4USD { get; set; }

        public decimal EndDebitAccountEURO { get; set; }

        public decimal EndDebitAccountVND4EURO { get; set; }

        public decimal EndDebitAccountRMB { get; set; }

        public decimal EndDebitAccountVND4RMB { get; set; }

        public decimal EndDebitAccountSGD { get; set; }

        public decimal EndDebitAccountVND4SGD { get; set; }

        public decimal EndDebitAccountGBP { get; set; }

        public decimal EndDebitAccountVND4GBP { get; set; }

        public decimal ACDocumentEntrySegmentID { get; set; }

        public string ACDocumentEntrySegmentName { get; set; }

        #endregion

        #endregion

        #region Debit, credit amount and balance
        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal DocumentReceiptAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal DocumentPaymentAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal ACDocumentEntryCreditAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal ACDocumentEntryCreditAmountUSD { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal ACDocumentEntryCreditExchangeAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal CreditExchangeAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal ACDocumentEntryDebitAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal ACDocumentEntryDebitAmountUSD { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal ACDocumentEntryDebitExchangeAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal DebitExchangeAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal StartPeriodBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal StartPeriodExchangeBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal StartPeriodDebitBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal StartPeriodDebitBalanceUSD { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal StartPeriodDebitExchangeBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal StartPeriodCreditBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal StartPeriodCreditBalanceUSD { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal StartPeriodCreditExchangeBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndPeriodBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndPeriodExchangeBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndPeriodDebitBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndPeriodDebitBalanceUSD { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndPeriodDebitExchangeBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndPeriodCreditBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndPeriodCreditBalanceUSD { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndPeriodCreditExchangeBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndYearDebitAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndYearCreditAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndYearDebitAmountUSD { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal EndYearCreditAmountUSD { get; set; }


        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal AccountBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal AccountExchangeBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal AccountDebitBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal AccountCreditBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal AccountDebitBalanceUSD { get; set; }

        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal AccountCreditBalanceUSD { get; set; }
        #endregion

        #region Asset properties
        public string ACAssetNo { get; set; }

        public string ACAssetName { get; set; }

        public string ACAssetType { get; set; }

        public string ACAssetTypeDisplayedText { get; set; }

        public DateTime ACAssetUsedDate { get; set; }

        public string ACAssetModelNo { get; set; }

        public string ACAssetAccountNo { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal ACAssetOriginalAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPercent)]
        public decimal ACAssetDepreciationPercent { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal ACAssetDepreciationAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal ACAssetDepreciatedAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal ACAssetTotalDepreciatedAmount { get; set; }

        public DateTime ACAssetDepreciationDate { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupQty)]
        public decimal ACAssetExpiryMonths { get; set; }

        public DateTime ACAssetPurchasedDate { get; set; }

        public string ACAssetComment { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupQty)]
        public decimal AssetReceiptedQty { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupQty)]
        public decimal AssetShippedQty { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal AssetReceiptedAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal AssetShippedAmount { get; set; }

        public int HRDepartmentRoomID { get; set; }

        #endregion

        #region Equipment properties
        public string EquipmentNo { get; set; }

        public string EquipmentName { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupQty)]
        public decimal EquipmentReceiptedQty { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupQty)]
        public decimal EquipmentShippedQty { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal EquipmentOriginalAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal EquipmentReceiptedAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal EquipmentShippedAmount { get; set; }

        public string ICProductSerieNo { get; set; }

        public decimal ICEquipmentDepreciatedAmount { get; set; }

        public string ICEquipmentVoucherNo { get; set; }

        public decimal ICProductUnitPrice { get; set; }

        public int ReferedItemID { get; set; }

        #endregion

        #region Cost object
        public int ACCostObjectAllocationMonths { get; set; }

        public string ACCostObjectNo { get; set; }

        public string ACCostObjectName { get; set; }

        public int FK_ACCostAccountID { get; set; }

        public DateTime ACCostObjectStartDate { get; set; }

        public string CostObjectAccountNo { get; set; }

        public decimal CostObjectOriginalAmount { get; set; }

        public decimal CostObjectOpenRemainedAmount { get; set; }

        public decimal CostObjectTransactionDepreciatedAmount { get; set; }

        public decimal CostObjectEndRemainedAmount { get; set; }

        #endregion

        #region Invoice properties
        public string ARInvoiceNo { get; set; }

        public DateTime ARInvoiceDate { get; set; }

        public DateTime ARInvoiceDesc { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal ARInvoiceTotalAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal ARInvoiceDepositBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal ARInvoicePaymentAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal ARInvoiceReturnAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public decimal ARInvoiceBalanceDue { get; set; }

        public string ACDocumentVoucherNo { get; set; }

        #endregion

        public string ACDocumentEntryType { get; set; }
        public int ACAccountID { get; set; }
        public string ACAccountNo { get; set; }
        public string CreditAccountNo { get; set; }
        public string DebitAccountNo { get; set; }
        public string ACDocumentReference { get; set; }
        public string ACAccountReciprocalNo { get; set; }
        public bool IsOpeningBalance { get; set; }
        public bool IsEndBalance { get; set; }
        public int OrderNum { get; set; }
        public int FK_ARInvoiceID { get; set; }
        public decimal SumACDocumentEntryDebitAmount { get; set; }
        public decimal SumACDocumentEntryCreditAmount { get; set; }
        public int FK_HRDepartmentRoomID { get; set; }
        public int FK_HRDepartmentRoomGroupItemID { get; set; }
    }
    #endregion
}