using BOSLib;
using System;
namespace BOSERP
{
    #region ADRemindWorkings
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ADRemindWorkingsInfo
    //Created Date:Friday, March 15, 2019
    //-----------------------------------------------------------

    public class ADRemindWorkingsInfo : BusinessObject
    {
        public ADRemindWorkingsInfo()
        {
        }
        #region Variables
        protected int _aDRemindWorkingID;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_HREmployeeID;
        protected int _fK_HRDepartmentID;
        protected int _fK_HRDepartmentRoomID;
        protected String _aDRemindWorkingEmployeeRef = String.Empty;
        protected String _aDRemindWorkingDocumentNo = String.Empty;
        protected String _aDRemindWorkingDocumentName = String.Empty;
        protected String _aDRemindWorkingTitle = String.Empty;
        protected String _aDRemindWorkingContent = String.Empty;
        protected DateTime _aDRemindWorkingDate = DateTime.MaxValue;
        protected String _aDRemindWorkingType = String.Empty;
        protected String _aDRemindWorkingPriorityLevel = String.Empty;
        protected bool _aDRemindWorkingIsRead = true;
        #endregion

        #region Public properties
        public int ADRemindWorkingID
        {
            get { return _aDRemindWorkingID; }
            set
            {
                if (value != this._aDRemindWorkingID)
                {
                    _aDRemindWorkingID = value;
                    NotifyChanged("ADRemindWorkingID");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int FK_HRDepartmentID
        {
            get { return _fK_HRDepartmentID; }
            set
            {
                if (value != this._fK_HRDepartmentID)
                {
                    _fK_HRDepartmentID = value;
                    NotifyChanged("FK_HRDepartmentID");
                }
            }
        }
        public int FK_HRDepartmentRoomID
        {
            get { return _fK_HRDepartmentRoomID; }
            set
            {
                if (value != this._fK_HRDepartmentRoomID)
                {
                    _fK_HRDepartmentRoomID = value;
                    NotifyChanged("FK_HRDepartmentRoomID");
                }
            }
        }
        public String ADRemindWorkingEmployeeRef
        {
            get { return _aDRemindWorkingEmployeeRef; }
            set
            {
                if (value != this._aDRemindWorkingEmployeeRef)
                {
                    _aDRemindWorkingEmployeeRef = value;
                    NotifyChanged("ADRemindWorkingEmployeeRef");
                }
            }
        }
        public String ADRemindWorkingDocumentNo
        {
            get { return _aDRemindWorkingDocumentNo; }
            set
            {
                if (value != this._aDRemindWorkingDocumentNo)
                {
                    _aDRemindWorkingDocumentNo = value;
                    NotifyChanged("ADRemindWorkingDocumentNo");
                }
            }
        }
        public String ADRemindWorkingDocumentName
        {
            get { return _aDRemindWorkingDocumentName; }
            set
            {
                if (value != this._aDRemindWorkingDocumentName)
                {
                    _aDRemindWorkingDocumentName = value;
                    NotifyChanged("ADRemindWorkingDocumentName");
                }
            }
        }
        public String ADRemindWorkingTitle
        {
            get { return _aDRemindWorkingTitle; }
            set
            {
                if (value != this._aDRemindWorkingTitle)
                {
                    _aDRemindWorkingTitle = value;
                    NotifyChanged("ADRemindWorkingTitle");
                }
            }
        }
        public String ADRemindWorkingContent
        {
            get { return _aDRemindWorkingContent; }
            set
            {
                if (value != this._aDRemindWorkingContent)
                {
                    _aDRemindWorkingContent = value;
                    NotifyChanged("ADRemindWorkingContent");
                }
            }
        }
        public DateTime ADRemindWorkingDate
        {
            get { return _aDRemindWorkingDate; }
            set
            {
                if (value != this._aDRemindWorkingDate)
                {
                    _aDRemindWorkingDate = value;
                    NotifyChanged("ADRemindWorkingDate");
                }
            }
        }
        public String ADRemindWorkingType
        {
            get { return _aDRemindWorkingType; }
            set
            {
                if (value != this._aDRemindWorkingType)
                {
                    _aDRemindWorkingType = value;
                    NotifyChanged("ADRemindWorkingType");
                }
            }
        }
        public String ADRemindWorkingPriorityLevel
        {
            get { return _aDRemindWorkingPriorityLevel; }
            set
            {
                if (value != this._aDRemindWorkingPriorityLevel)
                {
                    _aDRemindWorkingPriorityLevel = value;
                    NotifyChanged("ADRemindWorkingPriorityLevel");
                }
            }
        }
        public bool ADRemindWorkingIsRead
        {
            get { return _aDRemindWorkingIsRead; }
            set
            {
                if (value != this._aDRemindWorkingIsRead)
                {
                    _aDRemindWorkingIsRead = value;
                    NotifyChanged("ADRemindWorkingIsRead");
                }
            }
        }
        #endregion

        public DateTime ADRemindWorkingFromDate { get; set; }

        public DateTime ADRemindWorkingToDate { get; set; }
    }
    #endregion
}