using BOSLib;
using System;
using System.Collections.Generic;
using System.Drawing;
namespace BOSERP
{
    #region MMBatchProductProductionNormItems
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MMBatchProductProductionNormItemsInfo
    //Created Date:Thursday, November 05, 2015
    //-----------------------------------------------------------

    public class MMBatchProductProductionNormItemsInfo : BOSTreeListObject
    {
        public MMBatchProductProductionNormItemsInfo()
        {
        }
        #region Variables
        protected int _mMBatchProductProductionNormItemID;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_MMBatchProductID;
        protected int _fK_MMProductionNormID;
        protected int _fK_MMProductionNormItemID;
        protected int _fK_ICProductID;
        protected int _fK_ICDepartmentID;
        protected int _fK_ICProductGroupID;
        protected int _fK_ICMeasureUnitID;
        protected int _fK_MMFormulaIDPaintA;
        protected int _fK_MMFormulaIDPaintB;
        protected int _fK_MMFormulaIDVeneer;
        protected int _fK_ICProductIDReuse;
        protected int _fK_ICProductIDPack;
        protected String _mMBatchProductProductionNormItemParentNo = String.Empty;
        protected int _mMBatchProductProductionNormItemParentID;
        protected String _mMBatchProductProductionNormItemGroup = String.Empty;
        protected String _mMBatchProductProductionNormItemUnit = String.Empty;
        protected bool _mMBatchProductProductionNormItemIsComponent = true;
        protected String _mMBatchProductProductionNormItemNo = String.Empty;
        protected String _mMBatchProductProductionNormItemProductName = String.Empty;
        protected String _mMBatchProductProductionNormItemProductSupplierName = String.Empty;
        protected String _mMBatchProductProductionNormItemProductSupplierNumber = String.Empty;
        protected String _mMBatchProductProductionNormItemProductAttribute = String.Empty;
        protected decimal _mMBatchProductProductionNormItemQuantity;
        protected decimal _mMBatchProductProductionNormItemProductLength;
        protected decimal _mMBatchProductProductionNormItemProductHeight;
        protected decimal _mMBatchProductProductionNormItemProductWidth;
        protected int _mMBatchProductProductionNormItemSortOrder;
        protected String _mMBatchProductProductionNormItemProductSizeAndPacking = String.Empty;
        protected String _mMBatchProductProductionNormItemProductWoodType = String.Empty;
        protected String _mMBatchProductProductionNormItemProductJoinery = String.Empty;
        protected decimal _mMBatchProductProductionNormItemBlocks;
        protected decimal _mMBatchProductProductionNormItemMDFBlocks;
        protected decimal _mMBatchProductProductionNormItemVeneer;
        protected decimal _mMBatchProductProductionNormItemPlywood;
        protected decimal _mMBatchProductProductionNormItemPaintA;
        protected decimal _mMBatchProductProductionNormItemPaintB;
        protected decimal _mMBatchProductProductionNormItemTotalQuantity;
        protected decimal _mMBatchProductProductionNormItemTotalWoodConsumable;
        protected String _mMBatchProductProductionNormItemParentOrderName = String.Empty;
        protected decimal _mMBatchProductProductionNormItemAcreage;
        protected decimal _mMBatchProductProductionNormItemDepreciationRate;
        protected decimal _mMBatchProductProductionNormItemActualDepreciationRate;
        protected bool _mMBatchProductProductionNormItemIsReuse = true;
        protected String _mMBatchProductProductionNormItemVeneerKey = String.Empty;
        protected decimal _mMBatchProductProductionNormItemHardwareAssembleQuantity;
        protected decimal _mMBatchProductProductionNormItemHardwareAllocationQuantity;
        protected String _mMBatchProductProductionNormItemPaintAKey = String.Empty;
        protected String _mMBatchProductProductionNormItemPaintBKey = String.Empty;
        protected DateTime _mMBatchProductProductionNormItemNeededTime = DateTime.MaxValue;
        protected decimal _mMBatchProductProductionNormItemPackagingGW;
        protected decimal _mMBatchProductProductionNormItemPackagingNW;
        protected decimal _mMBatchProductProductionNormItemPackagingAllocationTotalQuantity;
        protected String _mMBatchProductProductionNormItemSerialNo = String.Empty;
        protected int _fK_ICProductWoodIngredientID;
        protected decimal _mMBatchProductProductionNormItemWoodBlocks;
        protected int _fK_ICProductAttributeSpecialityID;
        protected String _mMBatchProductProductionNormItemComment = String.Empty;
        protected String _mMBatchProductProductionNormItemProductDesc = String.Empty;
        protected String _mMBatchProductProductionNormItemPaintMixRatio = String.Empty;
        protected decimal _mMBatchProductProductionNormItemProductOverallDimensionHeight;
        protected decimal _mMBatchProductProductionNormItemProductOverallDimensionWidth;
        protected decimal _mMBatchProductProductionNormItemProductOverallDimensionLength;
        protected String _mMBatchProductProductionNormItemProductWeightPerVolume = String.Empty;
        protected decimal _mMBatchProductProductionNormItemProductInsideDimensionHeight;
        protected decimal _mMBatchProductProductionNormItemProductInsideDimensionWidth;
        protected decimal _mMBatchProductProductionNormItemProductInsideDimensionLength;
        protected int _fK_MMBatchProductItemID;
        protected int _fK_ICProductForBatchID;
        protected String _mMBatchProductProductionNormItemResourceType = String.Empty;
        protected String _mMBatchProductProductionNormItemModifiedStatus = DefaultStatus;
        protected int _fK_APSupplierID;
        protected int _fK_ICProdAttPackingMaterialSpecialityID;
        protected int _fK_ICProdAttPackingMaterialSizeID;
        protected int _fK_ICProdAttPackingMaterialWeightPerVolumeID;
        protected decimal _mMBatchProductProductionNormItemBlockPerOne;
        protected decimal _mMBatchProductProductionNormItemQuantityPerOne;
        protected String _mMBatchProductProductionNormItemImage = String.Empty;
        protected String _mMBatchProductProductionNormItemFrontCNCImage = String.Empty;
        protected String _mMBatchProductProductionNormItemBacksideCNCImage = String.Empty;
        protected bool _mMBatchProductProductionNormItemIsBurnishing = true;
        protected int _fK_ICProductAttributeWoodTypeID;
        protected int _fK_MMProductionNormApproveLogID;
        protected String _mMBatchProductProductionNormItemBarcode = String.Empty;
        protected int _fK_ICProductAttributeQualityID;
        protected int _fK_MMOperationID;
        protected int _fK_MMBPSemiProductID;
        protected String _mMBatchProductProductionNormItemExecuteType = String.Empty;
        protected String _mMBatchProductProductionNormItemSerial = String.Empty;
        protected decimal _mMBatchProductProductionNormItemDiameter;
        protected decimal _mMBatchProductProductionNormItemDepth;
        protected decimal _mMBatchProductProductionNormItemQuantitative;
        protected int _mMBatchProductProductionNormItemRef;
        protected String _mMBatchProductProductionNormItemType;
        protected string _mMBatchProductProductionNormItemCode01Combo = string.Empty;
        protected string _mMBatchProductProductionNormItemCode02Combo = string.Empty;
        protected string _mMBatchProductProductionNormItemCode03Combo = string.Empty;
        protected string _mMBatchProductProductionNormItemCode04Combo = string.Empty;
        protected string _mMBatchProductProductionNormItemCode05Combo = string.Empty;
        protected string _mMBatchProductProductionNormItemCode06Combo = string.Empty;
        protected string _mMBatchProductProductionNormItemCode07Combo = string.Empty;
        protected string _mMBatchProductProductionNormItemCode08Combo = string.Empty;
        protected string _mMBatchProductProductionNormItemCode09Combo = string.Empty;
        protected string _mMBatchProductProductionNormItemCode10Combo = string.Empty;
        protected string _mMBatchProductProductionNormItemColorDesc = string.Empty;
        protected string _mMBatchProductProductionNormItemOtherColor = string.Empty;
        protected string _mMBatchProductProductionNormItemComplexityType = string.Empty;
        protected decimal _mMBatchProductProductionNormItemPaintC;
        protected int _fK_MMFormulaIDPaintC;
        #endregion

        #region Public properties
        public int MMBatchProductProductionNormItemID
        {
            get { return _mMBatchProductProductionNormItemID; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemID)
                {
                    _mMBatchProductProductionNormItemID = value;
                    NotifyChanged("MMBatchProductProductionNormItemID");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_MMBatchProductID
        {
            get { return _fK_MMBatchProductID; }
            set
            {
                if (value != this._fK_MMBatchProductID)
                {
                    _fK_MMBatchProductID = value;
                    NotifyChanged("FK_MMBatchProductID");
                }
            }
        }
        public int FK_MMProductionNormID
        {
            get { return _fK_MMProductionNormID; }
            set
            {
                if (value != this._fK_MMProductionNormID)
                {
                    _fK_MMProductionNormID = value;
                    NotifyChanged("FK_MMProductionNormID");
                }
            }
        }
        public int FK_MMProductionNormItemID
        {
            get { return _fK_MMProductionNormItemID; }
            set
            {
                if (value != this._fK_MMProductionNormItemID)
                {
                    _fK_MMProductionNormItemID = value;
                    NotifyChanged("FK_MMProductionNormItemID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICDepartmentID
        {
            get { return _fK_ICDepartmentID; }
            set
            {
                if (value != this._fK_ICDepartmentID)
                {
                    _fK_ICDepartmentID = value;
                    NotifyChanged("FK_ICDepartmentID");
                }
            }
        }
        public int FK_ICProductGroupID
        {
            get { return _fK_ICProductGroupID; }
            set
            {
                if (value != this._fK_ICProductGroupID)
                {
                    _fK_ICProductGroupID = value;
                    NotifyChanged("FK_ICProductGroupID");
                }
            }
        }
        public int FK_ICMeasureUnitID
        {
            get { return _fK_ICMeasureUnitID; }
            set
            {
                if (value != this._fK_ICMeasureUnitID)
                {
                    _fK_ICMeasureUnitID = value;
                    NotifyChanged("FK_ICMeasureUnitID");
                }
            }
        }
        public int FK_MMFormulaIDPaintA
        {
            get { return _fK_MMFormulaIDPaintA; }
            set
            {
                if (value != this._fK_MMFormulaIDPaintA)
                {
                    _fK_MMFormulaIDPaintA = value;
                    NotifyChanged("FK_MMFormulaIDPaintA");
                }
            }
        }
        public int FK_MMFormulaIDPaintB
        {
            get { return _fK_MMFormulaIDPaintB; }
            set
            {
                if (value != this._fK_MMFormulaIDPaintB)
                {
                    _fK_MMFormulaIDPaintB = value;
                    NotifyChanged("FK_MMFormulaIDPaintB");
                }
            }
        }
        public int FK_MMFormulaIDVeneer
        {
            get { return _fK_MMFormulaIDVeneer; }
            set
            {
                if (value != this._fK_MMFormulaIDVeneer)
                {
                    _fK_MMFormulaIDVeneer = value;
                    NotifyChanged("FK_MMFormulaIDVeneer");
                }
            }
        }
        public int FK_ICProductIDReuse
        {
            get { return _fK_ICProductIDReuse; }
            set
            {
                if (value != this._fK_ICProductIDReuse)
                {
                    _fK_ICProductIDReuse = value;
                    NotifyChanged("FK_ICProductIDReuse");
                }
            }
        }
        public int FK_ICProductIDPack
        {
            get { return _fK_ICProductIDPack; }
            set
            {
                if (value != this._fK_ICProductIDPack)
                {
                    _fK_ICProductIDPack = value;
                    NotifyChanged("FK_ICProductIDPack");
                }
            }
        }
        public String MMBatchProductProductionNormItemParentNo
        {
            get { return _mMBatchProductProductionNormItemParentNo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemParentNo)
                {
                    _mMBatchProductProductionNormItemParentNo = value;
                    NotifyChanged("MMBatchProductProductionNormItemParentNo");
                }
            }
        }
        public int MMBatchProductProductionNormItemParentID
        {
            get { return _mMBatchProductProductionNormItemParentID; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemParentID)
                {
                    _mMBatchProductProductionNormItemParentID = value;
                    NotifyChanged("MMBatchProductProductionNormItemParentID");
                }
            }
        }
        public String MMBatchProductProductionNormItemGroup
        {
            get { return _mMBatchProductProductionNormItemGroup; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemGroup)
                {
                    _mMBatchProductProductionNormItemGroup = value;
                    NotifyChanged("MMBatchProductProductionNormItemGroup");
                }
            }
        }
        public String MMBatchProductProductionNormItemUnit
        {
            get { return _mMBatchProductProductionNormItemUnit; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemUnit)
                {
                    _mMBatchProductProductionNormItemUnit = value;
                    NotifyChanged("MMBatchProductProductionNormItemUnit");
                }
            }
        }
        public bool MMBatchProductProductionNormItemIsComponent
        {
            get { return _mMBatchProductProductionNormItemIsComponent; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemIsComponent)
                {
                    _mMBatchProductProductionNormItemIsComponent = value;
                    NotifyChanged("MMBatchProductProductionNormItemIsComponent");
                }
            }
        }
        public String MMBatchProductProductionNormItemNo
        {
            get { return _mMBatchProductProductionNormItemNo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemNo)
                {
                    _mMBatchProductProductionNormItemNo = value;
                    NotifyChanged("MMBatchProductProductionNormItemNo");
                }
            }
        }
        public String MMBatchProductProductionNormItemProductName
        {
            get { return _mMBatchProductProductionNormItemProductName; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductName)
                {
                    _mMBatchProductProductionNormItemProductName = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductName");
                }
            }
        }
        public String MMBatchProductProductionNormItemProductSupplierName
        {
            get { return _mMBatchProductProductionNormItemProductSupplierName; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductSupplierName)
                {
                    _mMBatchProductProductionNormItemProductSupplierName = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductSupplierName");
                }
            }
        }
        public String MMBatchProductProductionNormItemProductSupplierNumber
        {
            get { return _mMBatchProductProductionNormItemProductSupplierNumber; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductSupplierNumber)
                {
                    _mMBatchProductProductionNormItemProductSupplierNumber = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductSupplierNumber");
                }
            }
        }
        public String MMBatchProductProductionNormItemProductAttribute
        {
            get { return _mMBatchProductProductionNormItemProductAttribute; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductAttribute)
                {
                    _mMBatchProductProductionNormItemProductAttribute = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductAttribute");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemQuantity
        {
            get { return _mMBatchProductProductionNormItemQuantity; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemQuantity)
                {
                    _mMBatchProductProductionNormItemQuantity = value;
                    NotifyChanged("MMBatchProductProductionNormItemQuantity");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemProductLength
        {
            get { return _mMBatchProductProductionNormItemProductLength; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductLength)
                {
                    _mMBatchProductProductionNormItemProductLength = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductLength");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemProductHeight
        {
            get { return _mMBatchProductProductionNormItemProductHeight; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductHeight)
                {
                    _mMBatchProductProductionNormItemProductHeight = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductHeight");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemProductWidth
        {
            get { return _mMBatchProductProductionNormItemProductWidth; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductWidth)
                {
                    _mMBatchProductProductionNormItemProductWidth = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductWidth");
                }
            }
        }
        public int MMBatchProductProductionNormItemSortOrder
        {
            get { return _mMBatchProductProductionNormItemSortOrder; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemSortOrder)
                {
                    _mMBatchProductProductionNormItemSortOrder = value;
                    NotifyChanged("MMBatchProductProductionNormItemSortOrder");
                }
            }
        }
        public String MMBatchProductProductionNormItemProductSizeAndPacking
        {
            get { return _mMBatchProductProductionNormItemProductSizeAndPacking; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductSizeAndPacking)
                {
                    _mMBatchProductProductionNormItemProductSizeAndPacking = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductSizeAndPacking");
                }
            }
        }
        public String MMBatchProductProductionNormItemProductWoodType
        {
            get { return _mMBatchProductProductionNormItemProductWoodType; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductWoodType)
                {
                    _mMBatchProductProductionNormItemProductWoodType = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductWoodType");
                }
            }
        }
        public String MMBatchProductProductionNormItemProductJoinery
        {
            get { return _mMBatchProductProductionNormItemProductJoinery; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductJoinery)
                {
                    _mMBatchProductProductionNormItemProductJoinery = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductJoinery");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemBlocks
        {
            get { return _mMBatchProductProductionNormItemBlocks; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemBlocks)
                {
                    _mMBatchProductProductionNormItemBlocks = value;
                    NotifyChanged("MMBatchProductProductionNormItemBlocks");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemMDFBlocks
        {
            get { return _mMBatchProductProductionNormItemMDFBlocks; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemMDFBlocks)
                {
                    _mMBatchProductProductionNormItemMDFBlocks = value;
                    NotifyChanged("MMBatchProductProductionNormItemMDFBlocks");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemVeneer
        {
            get { return _mMBatchProductProductionNormItemVeneer; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemVeneer)
                {
                    _mMBatchProductProductionNormItemVeneer = value;
                    NotifyChanged("MMBatchProductProductionNormItemVeneer");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemPlywood
        {
            get { return _mMBatchProductProductionNormItemPlywood; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemPlywood)
                {
                    _mMBatchProductProductionNormItemPlywood = value;
                    NotifyChanged("MMBatchProductProductionNormItemPlywood");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemPaintA
        {
            get { return _mMBatchProductProductionNormItemPaintA; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemPaintA)
                {
                    _mMBatchProductProductionNormItemPaintA = value;
                    NotifyChanged("MMBatchProductProductionNormItemPaintA");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemPaintB
        {
            get { return _mMBatchProductProductionNormItemPaintB; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemPaintB)
                {
                    _mMBatchProductProductionNormItemPaintB = value;
                    NotifyChanged("MMBatchProductProductionNormItemPaintB");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemTotalQuantity
        {
            get { return _mMBatchProductProductionNormItemTotalQuantity; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemTotalQuantity)
                {
                    _mMBatchProductProductionNormItemTotalQuantity = value;
                    NotifyChanged("MMBatchProductProductionNormItemTotalQuantity");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemTotalWoodConsumable
        {
            get { return _mMBatchProductProductionNormItemTotalWoodConsumable; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemTotalWoodConsumable)
                {
                    _mMBatchProductProductionNormItemTotalWoodConsumable = value;
                    NotifyChanged("MMBatchProductProductionNormItemTotalWoodConsumable");
                }
            }
        }
        public String MMBatchProductProductionNormItemParentOrderName
        {
            get { return _mMBatchProductProductionNormItemParentOrderName; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemParentOrderName)
                {
                    _mMBatchProductProductionNormItemParentOrderName = value;
                    NotifyChanged("MMBatchProductProductionNormItemParentOrderName");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemAcreage
        {
            get { return _mMBatchProductProductionNormItemAcreage; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemAcreage)
                {
                    _mMBatchProductProductionNormItemAcreage = value;
                    NotifyChanged("MMBatchProductProductionNormItemAcreage");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemDepreciationRate
        {
            get { return _mMBatchProductProductionNormItemDepreciationRate; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemDepreciationRate)
                {
                    _mMBatchProductProductionNormItemDepreciationRate = value;
                    NotifyChanged("MMBatchProductProductionNormItemDepreciationRate");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemActualDepreciationRate
        {
            get { return _mMBatchProductProductionNormItemActualDepreciationRate; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemActualDepreciationRate)
                {
                    _mMBatchProductProductionNormItemActualDepreciationRate = value;
                    NotifyChanged("MMBatchProductProductionNormItemActualDepreciationRate");
                }
            }
        }
        public bool MMBatchProductProductionNormItemIsReuse
        {
            get { return _mMBatchProductProductionNormItemIsReuse; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemIsReuse)
                {
                    _mMBatchProductProductionNormItemIsReuse = value;
                    NotifyChanged("MMBatchProductProductionNormItemIsReuse");
                }
            }
        }
        public String MMBatchProductProductionNormItemVeneerKey
        {
            get { return _mMBatchProductProductionNormItemVeneerKey; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemVeneerKey)
                {
                    _mMBatchProductProductionNormItemVeneerKey = value;
                    NotifyChanged("MMBatchProductProductionNormItemVeneerKey");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemHardwareAssembleQuantity
        {
            get { return _mMBatchProductProductionNormItemHardwareAssembleQuantity; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemHardwareAssembleQuantity)
                {
                    _mMBatchProductProductionNormItemHardwareAssembleQuantity = value;
                    NotifyChanged("MMBatchProductProductionNormItemHardwareAssembleQuantity");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemHardwareAllocationQuantity
        {
            get { return _mMBatchProductProductionNormItemHardwareAllocationQuantity; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemHardwareAllocationQuantity)
                {
                    _mMBatchProductProductionNormItemHardwareAllocationQuantity = value;
                    NotifyChanged("MMBatchProductProductionNormItemHardwareAllocationQuantity");
                }
            }
        }
        public String MMBatchProductProductionNormItemPaintAKey
        {
            get { return _mMBatchProductProductionNormItemPaintAKey; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemPaintAKey)
                {
                    _mMBatchProductProductionNormItemPaintAKey = value;
                    NotifyChanged("MMBatchProductProductionNormItemPaintAKey");
                }
            }
        }
        public String MMBatchProductProductionNormItemPaintBKey
        {
            get { return _mMBatchProductProductionNormItemPaintBKey; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemPaintBKey)
                {
                    _mMBatchProductProductionNormItemPaintBKey = value;
                    NotifyChanged("MMBatchProductProductionNormItemPaintBKey");
                }
            }
        }
        public DateTime MMBatchProductProductionNormItemNeededTime
        {
            get { return _mMBatchProductProductionNormItemNeededTime; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemNeededTime)
                {
                    _mMBatchProductProductionNormItemNeededTime = value;
                    NotifyChanged("MMBatchProductProductionNormItemNeededTime");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemPackagingGW
        {
            get { return _mMBatchProductProductionNormItemPackagingGW; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemPackagingGW)
                {
                    _mMBatchProductProductionNormItemPackagingGW = value;
                    NotifyChanged("MMBatchProductProductionNormItemPackagingGW");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemPackagingNW
        {
            get { return _mMBatchProductProductionNormItemPackagingNW; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemPackagingNW)
                {
                    _mMBatchProductProductionNormItemPackagingNW = value;
                    NotifyChanged("MMBatchProductProductionNormItemPackagingNW");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemPackagingAllocationTotalQuantity
        {
            get { return _mMBatchProductProductionNormItemPackagingAllocationTotalQuantity; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemPackagingAllocationTotalQuantity)
                {
                    _mMBatchProductProductionNormItemPackagingAllocationTotalQuantity = value;
                    NotifyChanged("MMBatchProductProductionNormItemPackagingAllocationTotalQuantity");
                }
            }
        }
        public String MMBatchProductProductionNormItemSerialNo
        {
            get { return _mMBatchProductProductionNormItemSerialNo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemSerialNo)
                {
                    _mMBatchProductProductionNormItemSerialNo = value;
                    NotifyChanged("MMBatchProductProductionNormItemSerialNo");
                }
            }
        }
        public int FK_ICProductWoodIngredientID
        {
            get { return _fK_ICProductWoodIngredientID; }
            set
            {
                if (value != this._fK_ICProductWoodIngredientID)
                {
                    _fK_ICProductWoodIngredientID = value;
                    NotifyChanged("FK_ICProductWoodIngredientID");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemWoodBlocks
        {
            get { return _mMBatchProductProductionNormItemWoodBlocks; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemWoodBlocks)
                {
                    _mMBatchProductProductionNormItemWoodBlocks = value;
                    NotifyChanged("MMBatchProductProductionNormItemWoodBlocks");
                }
            }
        }
        public int FK_ICProductAttributeSpecialityID
        {
            get { return _fK_ICProductAttributeSpecialityID; }
            set
            {
                if (value != this._fK_ICProductAttributeSpecialityID)
                {
                    _fK_ICProductAttributeSpecialityID = value;
                    NotifyChanged("FK_ICProductAttributeSpecialityID");
                }
            }
        }
        public String MMBatchProductProductionNormItemComment
        {
            get { return _mMBatchProductProductionNormItemComment; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemComment)
                {
                    _mMBatchProductProductionNormItemComment = value;
                    NotifyChanged("MMBatchProductProductionNormItemComment");
                }
            }
        }
        public String MMBatchProductProductionNormItemProductDesc
        {
            get { return _mMBatchProductProductionNormItemProductDesc; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductDesc)
                {
                    _mMBatchProductProductionNormItemProductDesc = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductDesc");
                }
            }
        }
        public String MMBatchProductProductionNormItemPaintMixRatio
        {
            get { return _mMBatchProductProductionNormItemPaintMixRatio; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemPaintMixRatio)
                {
                    _mMBatchProductProductionNormItemPaintMixRatio = value;
                    NotifyChanged("MMBatchProductProductionNormItemPaintMixRatio");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemProductOverallDimensionHeight
        {
            get { return _mMBatchProductProductionNormItemProductOverallDimensionHeight; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductOverallDimensionHeight)
                {
                    _mMBatchProductProductionNormItemProductOverallDimensionHeight = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductOverallDimensionHeight");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemProductOverallDimensionWidth
        {
            get { return _mMBatchProductProductionNormItemProductOverallDimensionWidth; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductOverallDimensionWidth)
                {
                    _mMBatchProductProductionNormItemProductOverallDimensionWidth = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductOverallDimensionWidth");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemProductOverallDimensionLength
        {
            get { return _mMBatchProductProductionNormItemProductOverallDimensionLength; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductOverallDimensionLength)
                {
                    _mMBatchProductProductionNormItemProductOverallDimensionLength = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductOverallDimensionLength");
                }
            }
        }
        public String MMBatchProductProductionNormItemProductWeightPerVolume
        {
            get { return _mMBatchProductProductionNormItemProductWeightPerVolume; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductWeightPerVolume)
                {
                    _mMBatchProductProductionNormItemProductWeightPerVolume = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductWeightPerVolume");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemProductInsideDimensionHeight
        {
            get { return _mMBatchProductProductionNormItemProductInsideDimensionHeight; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductInsideDimensionHeight)
                {
                    _mMBatchProductProductionNormItemProductInsideDimensionHeight = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductInsideDimensionHeight");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemProductInsideDimensionWidth
        {
            get { return _mMBatchProductProductionNormItemProductInsideDimensionWidth; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductInsideDimensionWidth)
                {
                    _mMBatchProductProductionNormItemProductInsideDimensionWidth = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductInsideDimensionWidth");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemProductInsideDimensionLength
        {
            get { return _mMBatchProductProductionNormItemProductInsideDimensionLength; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemProductInsideDimensionLength)
                {
                    _mMBatchProductProductionNormItemProductInsideDimensionLength = value;
                    NotifyChanged("MMBatchProductProductionNormItemProductInsideDimensionLength");
                }
            }
        }
        public int FK_MMBatchProductItemID
        {
            get { return _fK_MMBatchProductItemID; }
            set
            {
                if (value != this._fK_MMBatchProductItemID)
                {
                    _fK_MMBatchProductItemID = value;
                    NotifyChanged("FK_MMBatchProductItemID");
                }
            }
        }
        public int FK_ICProductForBatchID
        {
            get { return _fK_ICProductForBatchID; }
            set
            {
                if (value != this._fK_ICProductForBatchID)
                {
                    _fK_ICProductForBatchID = value;
                    NotifyChanged("FK_ICProductForBatchID");
                }
            }
        }
        public String MMBatchProductProductionNormItemResourceType
        {
            get { return _mMBatchProductProductionNormItemResourceType; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemResourceType)
                {
                    _mMBatchProductProductionNormItemResourceType = value;
                    NotifyChanged("MMBatchProductProductionNormItemResourceType");
                }
            }
        }
        public String MMBatchProductProductionNormItemModifiedStatus
        {
            get { return _mMBatchProductProductionNormItemModifiedStatus; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemModifiedStatus)
                {
                    _mMBatchProductProductionNormItemModifiedStatus = value;
                    NotifyChanged("MMBatchProductProductionNormItemModifiedStatus");
                }
            }
        }
        public int FK_APSupplierID
        {
            get { return _fK_APSupplierID; }
            set
            {
                if (value != this._fK_APSupplierID)
                {
                    _fK_APSupplierID = value;
                    NotifyChanged("FK_APSupplierID");
                }
            }
        }
        public int FK_ICProdAttPackingMaterialSpecialityID
        {
            get { return _fK_ICProdAttPackingMaterialSpecialityID; }
            set
            {
                if (value != this._fK_ICProdAttPackingMaterialSpecialityID)
                {
                    _fK_ICProdAttPackingMaterialSpecialityID = value;
                    NotifyChanged("FK_ICProdAttPackingMaterialSpecialityID");
                }
            }
        }
        public int FK_ICProdAttPackingMaterialSizeID
        {
            get { return _fK_ICProdAttPackingMaterialSizeID; }
            set
            {
                if (value != this._fK_ICProdAttPackingMaterialSizeID)
                {
                    _fK_ICProdAttPackingMaterialSizeID = value;
                    NotifyChanged("FK_ICProdAttPackingMaterialSizeID");
                }
            }
        }
        public int FK_ICProdAttPackingMaterialWeightPerVolumeID
        {
            get { return _fK_ICProdAttPackingMaterialWeightPerVolumeID; }
            set
            {
                if (value != this._fK_ICProdAttPackingMaterialWeightPerVolumeID)
                {
                    _fK_ICProdAttPackingMaterialWeightPerVolumeID = value;
                    NotifyChanged("FK_ICProdAttPackingMaterialWeightPerVolumeID");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemBlockPerOne
        {
            get { return _mMBatchProductProductionNormItemBlockPerOne; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemBlockPerOne)
                {
                    _mMBatchProductProductionNormItemBlockPerOne = value;
                    NotifyChanged("MMBatchProductProductionNormItemBlockPerOne");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemQuantityPerOne
        {
            get { return _mMBatchProductProductionNormItemQuantityPerOne; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemQuantityPerOne)
                {
                    _mMBatchProductProductionNormItemQuantityPerOne = value;
                    NotifyChanged("MMBatchProductProductionNormItemQuantityPerOne");
                }
            }
        }
        public String MMBatchProductProductionNormItemImage
        {
            get { return _mMBatchProductProductionNormItemImage; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemImage)
                {
                    _mMBatchProductProductionNormItemImage = value;
                    NotifyChanged("MMBatchProductProductionNormItemImage");
                }
            }
        }
        public String MMBatchProductProductionNormItemFrontCNCImage
        {
            get { return _mMBatchProductProductionNormItemFrontCNCImage; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemFrontCNCImage)
                {
                    _mMBatchProductProductionNormItemFrontCNCImage = value;
                    NotifyChanged("MMBatchProductProductionNormItemFrontCNCImage");
                }
            }
        }
        public String MMBatchProductProductionNormItemBacksideCNCImage
        {
            get { return _mMBatchProductProductionNormItemBacksideCNCImage; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemBacksideCNCImage)
                {
                    _mMBatchProductProductionNormItemBacksideCNCImage = value;
                    NotifyChanged("MMBatchProductProductionNormItemBacksideCNCImage");
                }
            }
        }
        public bool MMBatchProductProductionNormItemIsBurnishing
        {
            get { return _mMBatchProductProductionNormItemIsBurnishing; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemIsBurnishing)
                {
                    _mMBatchProductProductionNormItemIsBurnishing = value;
                    NotifyChanged("MMBatchProductProductionNormItemIsBurnishing");
                }
            }
        }
        public int FK_ICProductAttributeWoodTypeID
        {
            get { return _fK_ICProductAttributeWoodTypeID; }
            set
            {
                if (value != this._fK_ICProductAttributeWoodTypeID)
                {
                    _fK_ICProductAttributeWoodTypeID = value;
                    NotifyChanged("FK_ICProductAttributeWoodTypeID");
                }
            }
        }
        public int FK_MMProductionNormApproveLogID
        {
            get { return _fK_MMProductionNormApproveLogID; }
            set
            {
                if (value != this._fK_MMProductionNormApproveLogID)
                {
                    _fK_MMProductionNormApproveLogID = value;
                    NotifyChanged("FK_MMProductionNormApproveLogID");
                }
            }
        }
        public String MMBatchProductProductionNormItemBarcode
        {
            get { return _mMBatchProductProductionNormItemBarcode; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemBarcode)
                {
                    _mMBatchProductProductionNormItemBarcode = value;
                    NotifyChanged("MMBatchProductProductionNormItemBarcode");
                }
            }
        }
        public int FK_ICProductAttributeQualityID
        {
            get { return _fK_ICProductAttributeQualityID; }
            set
            {
                if (value != this._fK_ICProductAttributeQualityID)
                {
                    _fK_ICProductAttributeQualityID = value;
                    NotifyChanged("FK_ICProductAttributeQualityID");
                }
            }
        }
        public int FK_MMOperationID
        {
            get { return _fK_MMOperationID; }
            set
            {
                if (value != this._fK_MMOperationID)
                {
                    _fK_MMOperationID = value;
                    NotifyChanged("FK_MMOperationID");
                }
            }
        }
        public int FK_MMBPSemiProductID
        {
            get { return _fK_MMBPSemiProductID; }
            set
            {
                if (value != this._fK_MMBPSemiProductID)
                {
                    _fK_MMBPSemiProductID = value;
                    NotifyChanged("FK_MMBPSemiProductID");
                }
            }
        }
        public String MMBatchProductProductionNormItemExecuteType
        {
            get { return _mMBatchProductProductionNormItemExecuteType; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemExecuteType)
                {
                    _mMBatchProductProductionNormItemExecuteType = value;
                    NotifyChanged("MMBatchProductProductionNormItemExecuteType");
                }
            }
        }
        public String MMBatchProductProductionNormItemSerial
        {
            get { return _mMBatchProductProductionNormItemSerial; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemSerial)
                {
                    _mMBatchProductProductionNormItemSerial = value;
                    NotifyChanged("MMBatchProductProductionNormItemSerial");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemDiameter
        {
            get { return _mMBatchProductProductionNormItemDiameter; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemDiameter)
                {
                    _mMBatchProductProductionNormItemDiameter = value;
                    NotifyChanged("MMBatchProductProductionNormItemDiameter");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemDepth
        {
            get { return _mMBatchProductProductionNormItemDepth; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemDepth)
                {
                    _mMBatchProductProductionNormItemDepth = value;
                    NotifyChanged("MMBatchProductProductionNormItemDepth");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemQuantitative
        {
            get { return _mMBatchProductProductionNormItemQuantitative; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemQuantitative)
                {
                    _mMBatchProductProductionNormItemQuantitative = value;
                    NotifyChanged("MMBatchProductProductionNormItemQuantitative");
                }
            }
        }
        public int MMBatchProductProductionNormItemRef
        {
            get { return _mMBatchProductProductionNormItemRef; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemRef)
                {
                    _mMBatchProductProductionNormItemRef = value;
                    NotifyChanged("MMBatchProductProductionNormItemRef");
                }
            }
        }
        public String MMBatchProductProductionNormItemType
        {
            get { return _mMBatchProductProductionNormItemType; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemType)
                {
                    _mMBatchProductProductionNormItemType = value;
                    NotifyChanged("MMBatchProductProductionNormItemType");
                }
            }
        }
        public string MMBatchProductProductionNormItemCode01Combo
        {
            get { return _mMBatchProductProductionNormItemCode01Combo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemCode01Combo)
                {
                    _mMBatchProductProductionNormItemCode01Combo = value;
                    NotifyChanged("MMBatchProductProductionNormItemCode01Combo");
                }
            }
        }
        public string MMBatchProductProductionNormItemCode02Combo
        {
            get { return _mMBatchProductProductionNormItemCode02Combo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemCode02Combo)
                {
                    _mMBatchProductProductionNormItemCode02Combo = value;
                    NotifyChanged("MMBatchProductProductionNormItemCode02Combo");
                }
            }
        }
        public string MMBatchProductProductionNormItemCode03Combo
        {
            get { return _mMBatchProductProductionNormItemCode03Combo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemCode03Combo)
                {
                    _mMBatchProductProductionNormItemCode03Combo = value;
                    NotifyChanged("MMBatchProductProductionNormItemCode03Combo");
                }
            }
        }
        public string MMBatchProductProductionNormItemCode04Combo
        {
            get { return _mMBatchProductProductionNormItemCode04Combo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemCode04Combo)
                {
                    _mMBatchProductProductionNormItemCode04Combo = value;
                    NotifyChanged("MMBatchProductProductionNormItemCode04Combo");
                }
            }
        }
        public string MMBatchProductProductionNormItemCode05Combo
        {
            get { return _mMBatchProductProductionNormItemCode05Combo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemCode05Combo)
                {
                    _mMBatchProductProductionNormItemCode05Combo = value;
                    NotifyChanged("MMBatchProductProductionNormItemCode05Combo");
                }
            }
        }
        public string MMBatchProductProductionNormItemCode06Combo
        {
            get { return _mMBatchProductProductionNormItemCode06Combo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemCode06Combo)
                {
                    _mMBatchProductProductionNormItemCode06Combo = value;
                    NotifyChanged("MMBatchProductProductionNormItemCode06Combo");
                }
            }
        }
        public string MMBatchProductProductionNormItemCode07Combo
        {
            get { return _mMBatchProductProductionNormItemCode07Combo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemCode07Combo)
                {
                    _mMBatchProductProductionNormItemCode07Combo = value;
                    NotifyChanged("MMBatchProductProductionNormItemCode07Combo");
                }
            }
        }
        public string MMBatchProductProductionNormItemCode08Combo
        {
            get { return _mMBatchProductProductionNormItemCode08Combo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemCode08Combo)
                {
                    _mMBatchProductProductionNormItemCode08Combo = value;
                    NotifyChanged("MMBatchProductProductionNormItemCode08Combo");
                }
            }
        }
        public string MMBatchProductProductionNormItemCode09Combo
        {
            get { return _mMBatchProductProductionNormItemCode09Combo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemCode09Combo)
                {
                    _mMBatchProductProductionNormItemCode09Combo = value;
                    NotifyChanged("MMBatchProductProductionNormItemCode09Combo");
                }
            }
        }
        public string MMBatchProductProductionNormItemCode10Combo
        {
            get { return _mMBatchProductProductionNormItemCode10Combo; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemCode10Combo)
                {
                    _mMBatchProductProductionNormItemCode10Combo = value;
                    NotifyChanged("MMBatchProductProductionNormItemCode10Combo");
                }
            }
        }
        public string MMBatchProductProductionNormItemColorDesc
        {
            get { return _mMBatchProductProductionNormItemColorDesc; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemColorDesc)
                {
                    _mMBatchProductProductionNormItemColorDesc = value;
                    NotifyChanged("MMBatchProductProductionNormItemColorDesc");
                }
            }
        }
        public string MMBatchProductProductionNormItemOtherColor
        {
            get { return _mMBatchProductProductionNormItemOtherColor; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemOtherColor)
                {
                    _mMBatchProductProductionNormItemOtherColor = value;
                    NotifyChanged("MMBatchProductProductionNormItemOtherColor");
                }
            }
        }
        public string MMBatchProductProductionNormItemComplexityType
        {
            get { return _mMBatchProductProductionNormItemComplexityType; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemComplexityType)
                {
                    _mMBatchProductProductionNormItemComplexityType = value;
                    NotifyChanged("MMBatchProductProductionNormItemComplexityType");
                }
            }
        }
        public decimal MMBatchProductProductionNormItemPaintC
        {
            get { return _mMBatchProductProductionNormItemPaintC; }
            set
            {
                if (value != this._mMBatchProductProductionNormItemPaintC)
                {
                    _mMBatchProductProductionNormItemPaintC = value;
                    NotifyChanged("MMBatchProductProductionNormItemPaintC");
                }
            }
        }
        public int FK_MMFormulaIDPaintC
        {
            get { return _fK_MMFormulaIDPaintC; }
            set
            {
                if (value != this._fK_MMFormulaIDPaintC)
                {
                    _fK_MMFormulaIDPaintC = value;
                    NotifyChanged("FK_MMFormulaIDPaintC");
                }
            }
        }
        #endregion



        #region Extra properties
        public decimal SoLuongCum { get; set; }
        public string MMProductionNormNo { get; set; }
        public DateTime MMProductionNormPromulgateDate { get; set; }
        public int MMProductionNormVersion { get; set; }
        public string MMProductionNormType { get; set; }
        public string ARCustomerName { get; set; }

        public string ARSaleOrderNo { get; set; }
        public string ACObjectName { get; set; }
        public string MMBatchProductDesc { get; set; }
        public string MMBatchProductNo { get; set; }
        public decimal MMAllocationProposlItemQty { get; set; }
        public decimal MMAllocationPlanItemQty { get; set; }
        public decimal ICShipmentProductQty { get; set; }
        public decimal MMAllocatedQty { get; set; }
        public decimal MMAllocatedHWQty { get; set; }
        public decimal MMAllocatedHWAssembleQty { get; set; }
        public decimal MMAllocatedHWAllocationQty { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal ICReceiptItemProductQty { get; set; }
        //public List<MMBatchProductItemsInfo> List { get; set; }

        public string ICProductNo { get; set; }
        public string ICProductName { get; set; }
        public string ICProductName2 { get; set; }
        public string ICProductFBNo { get; set; }
        public string ICProductFBName { get; set; }

        public string MMProductDryHeight { get; set; }
        public decimal MMProductDryBlocks { get; set; }
        public decimal MMProductQty { get; set; }
        public decimal MMProductTotalQty { get; set; }
        public bool MMProductIsReuse { get; set; }
        public string ItemType { get; set; }
        public string DepartmentValue { get; set; }
        public string BatchProductItemSerial { get; set; }
        public string MMBatchProductProductionNormItemProductOverallDimension { get; set; }
        public string MMBatchProductProductionNormItemProductInsideDimension { get; set; }
        public string AttributeName { get; set; }
        public string MMBatchProductItemProductSerial { get; set; }
        public string ICMeasureUnitName { get; set; }

        public int MMBatchProductID { get; set; }
        public int MMProductionNormID { get; set; }
        public decimal MMBatchProductProductionNormItemRemainQty { get; set; }
        public DateTime MMBatchProductItemDeliveryDate { get; set; }
        public decimal MMBatchProductProductionNormItemQuantityPerUnit { get; set; }
        public decimal MMBatchProductProductionNormItemHWAssembleQuantityPerUnit { get; set; }
        public decimal MMBatchProductProductionNormItemHWAllocationQuantityPerUnit { get; set; }
        public decimal MMBatchProductItemProductQty { get; set; }
        public decimal MMShipmentQty { get; set; }
        public string ProductNo { get; set; }
        public string MMBatchProductProductionNormItemProductForBatchName { get; set; }
        public decimal PurchasePlanQty { get; set; }
        #endregion

        #region RP116 - Báo cáo chi tiết bán thành phẩm PHÔI
        public string LenhSanXuat { get; set; }
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MaChiTiet { get; set; }
        public string TenChiTietSP { get; set; }
        public string CongDoan { get; set; }
        public decimal SoLuongChiTietKeHoach { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal M3TinhKeHoach { get; set; }
        public decimal SoLuongSXThucTe { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal M3ThucTe { get; set; }
        public decimal SoLuongThieu { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal M3Thieu { get; set; }
        public decimal DayPhachGo { get; set; }
        public decimal M3GoKeHoach { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal M3ThucTeNhan { get; set; }
        public decimal M3GoConLai { get; set; }
        public decimal M3VuotDM { get; set; }
        public decimal TiLeTieuHao { get; set; }
        public string ThanhPham { get; set; }
        public decimal SoLuongVuot { get; set; }
        public decimal M3Vuot { get; set; }

        #endregion
        #region RP118
        public decimal SoLuongDaDinhHinh { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal M3DaDinhHinh { get; set; }
        public decimal SoLuongDaSoChe { get; set; }
        public decimal M3DaSoChe { get; set; }
        public decimal SoLuongDoDang { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal M3DoDang { get; set; }
        public string ChuyenDinhHinh { get; set; }
        #endregion
        #region RP119 - Báo cáo chi tiết bán thành phẩm LÁP RÁP
        public string MaCum { get; set; }
        public string TenCum { get; set; }
        public decimal M3CumKeHoach { get; set; }
        public decimal SoLuongCDTinhChe { get; set; }
        public decimal M3CDTinhChe { get; set; }
        // public decimal SoLuongDoDang { get; set; }
        //public decimal M3DoDang { get; set; }
        #region Báo cáo chi tiết bán thành phẩm Sơn
        public decimal M3CDXuatLapRap { set; get; }
        public decimal SoLuongXuatCDLapRap { set; get; }
        public decimal SoLuongCumChuaQuaSon { set; get; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal M3CumChuaQuaSon { set; get; }
        public decimal SoLuongCDLapRap { set; get; }
        public decimal M3CDLapRap { set; get; }
        #endregion
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal ICShipmentItemProductQty { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal SLVuotDM { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal SLdu { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal M2Dinhmuc { set; get; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal M2dodang { set; get; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal M2DaQuaSon { set; get; }
        //report 142
        public string MMBatchProductItemProductName { get; set; }
        public string MMBatchProductItemProductDesc { get; set; }
        public string MMBatchProductItemProductNo { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN3)]
        public decimal SLcum { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN3)]
        public decimal SLchitiet { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal Dai { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal Rong { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal Dayy { get; set; }
        public string Manguyenlieu { get; set; }
        public string Tennguyenlieu { get; set; }
        public string DVT { get; set; }
        public string Dactinh { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal SLRSS { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal STDG { get; set; }
        public string Mota { get; set; }
        public decimal SoLuongXuatCDLR { get; set; }
        public decimal M3XuatCDLR { get; set; }
        public decimal SLChiTietCuaCum { get; set; }
        public decimal SLChiTietDoDangChoLR { get; set; }
        public decimal SLCumThamKhao { get; set; }
        public decimal SoLuongCumKeHoach { get; set; }
        public decimal M3DoDangChoLapRap { get; set; }
        //public decimal M2Dinhmuc { get; set; }
        //public decimal M2dodang { get; set; }
        //public decimal M2DaQuaSon { get; set; }
        public int FK_ARCustomerID { get; set; }
        //
        //report 150
        public decimal MMBatchProductProductionNormItemPaint { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal KTinh { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal KLgoxe { get; set; }
        public string CPNL { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal KLXuatPK { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal KLNhapdoitra { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal Giatri { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal KLXuatthuc { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal sochenhlenh { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal phantramsoDM { get; set; }
        public string ICProductAttributeValue { get; set; }
        public string ICProductAttributeValueXK { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal GTNhapdoitra { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal Giatritong { get; set; }
        public string WoodTypeName { get; set; }
        public string ProductName { get; set; }
        public decimal ProductDryHeight { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal M3GoCuaCum { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal DTSonA { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal DTSonB { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal TongKhoiLuongTieuHao { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupQtyN2)]
        public decimal SLBTP { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal KLXuatthucGo { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal KLXuatthucBTP { get; set; }
        //end 150
        #endregion
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal ICReceiptItemProductQtyRedundant { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal ICReceiptItemProductQtyReturn { get; set; }
        public decimal QtyPerOne { get; set; }
        public decimal CanCancelQty { get; set; }
        public int FK_ICProductWoodTypeAttributeID { get; set; }
        public int FK_ICProductBasicUnitID { get; set; }
        public string KeyGroup { get; set; }


        #region RP174
        public decimal TongM3TinhTheoPG { get; set; }
        public decimal TongM3TinhTheoLSX { get; set; }
        public decimal TongM3TinhTheoHDCTG { get; set; }
        public decimal TongM3TinhDaXuat { get; set; }
        public decimal TongKLGoTronXuat { get; set; }
        public decimal TongKLGoXeNhap { get; set; }

        public decimal KLGoXe { get; set; }
        public decimal KLGoTron { get; set; }

        public decimal TongM3TinhGoTron { get; set; }

        public int ICShipmentID { get; set; }
        public int ICShipmentItemID { get; set; }
        public int FK_ICProductSerieID { get; set; }
        public string ICShipmentItemProductSerialNo { get; set; }
        public string ICShipmentItemLotNo { get; set; }
        public decimal ICShipmentItemProductUnitPrice { get; set; }

        public decimal SLNhap { get; set; }
        public string MMOperationName { get; set; }

        public string ProductForBatchNo { get; set; }
        public string ProductForBatchName { get; set; }
        #endregion
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal MMBatchProductProductionNormItemMeterialWoodBlocks { get; set; }
        public decimal MMBatchProductProductionNormItemMeterialHeigth { get; set; }
        public decimal MMBatchProductProductionNormItemMeterialLength { get; set; }
        public decimal MMBatchProductProductionNormItemMeterialWidth { get; set; }
        public decimal MMBatchProductProductionNormItemMeterialDepreciationQty { get; set; }
        public decimal MMBatchProductProductionNormItemMeterialDepreciationRate { get; set; }
        public string ICProductType { get; set; }
        public string ICProductTypeStr { get; set; }
        public int FK_ARSaleOrderID { get; set; }
        public string ARSaleOrderSaleAgreement { get; set; }
        public int FK_ARSaleOrderItemID { get; set; }
        [FormatGroup(FormatGroupAttribute.csFormatGroupN4)]
        public decimal MMBatchProductProductionNormItemMeterialWoodBlockNorm { get; set; }
        public string ICProductDesc { get; set; }
        public string MMPriority { get; set; }
        public bool RemoveOut { get; set; }
        public int MMBatchProductProductionNormItemMeterialID { get; set; }
        public string MMBatchProductProductionNormItemDesc { get; set; }
        public string ICProductFBDesc { get; set; }
        public string MMBatchProductItemGroupName { get; set; }

        //Print Routing
        public List<MMBatchProductProductionNormItemProcesssInfo> ProcessList { get; set; }
        public byte[] ICProductPicture { get; set; }
        public Image ProductImage { get; set; }
        public Image ProductItemImage { get; set; }
        public Image ProductBarcodeImage { get; set; }
        public string TTMT { get; set; }
        public string KTTinh { get; set; }
        public string ProductImageName { get; set; }
        public string ICProductCode { get; set; }
        public int MMPrintRoutingID { get; set; }
        public int FK_ICProductCarcassID { get; set; }
        public decimal ICProductSupplierPrice { get; set; }
        public decimal ProductCost { get; set; }
        public string MaterialItemDesc { get; set; }
        public string MaterialItemQty { get; set; }
        public string ComponentForCarcass { get; set; }
        public decimal MMPrintRoutingProductQty { get; set; }

        public decimal MMBatchProductProductionNormItemLRXQty { get; set; }
        public decimal MMBatchProductProductionNormItemLRCTQty { get; set; }
        public decimal ICInventoryStockQty { get; set; }
        public decimal MMBatchProductProductionNormItemPurchaseQty { get; set; }
        public string MMProductionNormItemProductWoodIngredientName { get; set; }
        public string ICProductAttributeWoodTypeName { get; set; }
        public decimal InvenQty { get; set; }


        public int NumChild { get; set; }

        public string ParentGroupOrderName { get; set; }
        public string ParentOrder { get; set; }
        public int ParentGroupOrder { get; set; }

        public int GroupOrder { get; set; }
        public string ItemOrder { get; set; }

        public string OrderName { get; set; }
        public int OrderNumber { get; set; }
        public int ParentOfParentID { get; set; }
        public string ARProposalName { get; set; }
        public decimal Blocks { get; set; }
        public decimal TotalBlock { get; set; }
        public int STT { get; set; }
        public int ProductLevel { get; set; }
        public string MMBatchProductItemPONo { get; set; }
        public string ICProductSupplierNumber { get; set; }
        public int MMOperationDetailPlanID { get; set; }
        public string MMProductType { get; set; }
        public decimal MMBatchProductProductionNormItemMeterialQty { get; set; }
        public decimal MMBatchProductProductionNormItemMeterialWaste { get; set; }
        public int FK_ICProductAlternativeID { get; set; }
        public int FK_MMLineID { get; set; }
        public int FK_MMWorkShopID { get; set; }
        public int FK_HRDepartmentRoomGroupItemID { get; set; }
        public int FK_MMParentProductionNormID { get; set; }
        public int FK_ICProductAttributeID { get; set; }
        public decimal MMPurchasePlanItemPurchaseProposalQty { get; set; }
        public decimal APProposalItemQty { get; set; }
        public decimal MMPurchasePlanItemInventoryStock { get; set; }
        public string MMWorkShopName { get; set; }
        public decimal SynchronousPercent { get; set; }
        public decimal MMOperationDetailPlanItemChildPlanProductQty { get; set; }
        public int FK_ICProductMaterialID { get; set; }
        public decimal MMAllocationPlanItemPlanedQty { get; set; }
        public decimal MMAllocationProposalItemQty { get; set; }
        public decimal MMAllocationPlanItemRemainQty { get; set; }
        public decimal MMWoodPlanItemDetailProductQty { get; set; }
        public string MMAllocationPlanItemStatus { get; set; }
        public string MMAllocationPlanItemReference { get; set; }
        public string MMAllocationPlanItemPostedStatus { get; set; }
        public string MMAllocationPlanItemPostedAction { get; set; }
        public int MMAllocationPlanItemID { get; set; }
        public DateTime MMBatchProductDate { get; set; }
        public bool SyncProductCheck { get; set; }
        public string MaterialType { get; set; }
        public decimal MMBatchProductProductionNormItemBPQty { get; set; }
        public decimal APProposalItemProductQty { get; set; }
        public string MMBPSemiProductName { get; set; }
        public string ICProductPackageNo { get; set; }
        public decimal MMAllocationPlanItemAltFactor { get; set; }
        public decimal MMBatchProductProductionNormItemUsedQty { get; set; }
        public int FK_MMBatchProductItemOutSourcingID { get; set; }
        public decimal MMAllocationPlanItemWoodQty { get; set; }
        public int ProductID { get; set; }
        public int ParentProductID { get; set; }
        public string MMFormulaName { get; set; }

        public string MMFormulaRef { get; set; }

        public string MMProductWoodTypeName { get; set; }

        public bool MMBatchProductProductionNormItemIsGrain { get; set; }

        public decimal ICInventoryStockOfBrachQty { get; set; }
        public int FK_HREmployeeIDReceive { get; set; }
        public string PrintByAndDate { get; set; }

        public string MMBatchProductProductionNormItemGroupText { get; set; }

        public Guid VirtualId { get; set; }

        public string AllocationTypeText { get; set; }
        public bool MMBatchProductProductionNormItemIsOverBTP { get; set; }

        public string MMBPSemiProductNo { get; set; }
        public bool IsProduct { get; set; }
        public int FK_ICProductAttributeTTMTID { get; set; }
        public string MMOperationNo { get; set; }
        public string APSupplierName { get; set; }
        public string MMBatchProductProductionNormPaintProcess { get; set; }
        public string MMBatchProductProductionNormStep { get; set; }
        public string MMBatchProductItemSOName { get; set; }

        #region PrintForm
        public DateTime MMBatchProductFromDate { get; set; }

        public DateTime MMBatchProductToDate { get; set; }

        public string MMBatchProductMultiCustomer { get; set; }

        public string HREmployeeCreateBOMName { get; set; }

        public DateTime AACreatedBOMDate { get; set; }

        public string HREmployeeUpdateBOMName { get; set; }

        public DateTime AAUpdatedBOMDate { get; set; }

        public string ICProductDetailCode02Combo { get; set; }

        public decimal MMBatchProductProductionNormItemNeedQuantity { get; set; }

        public decimal MMBatchProductProductionNormItemTSHH { get; set; }

        public decimal MMBatchProductProductionNormItemKLBTP { get; set; }

        public decimal MMBatchProductProductionNormItemTotalKLBTP { get; set; }

        public string MMBatchProductItemOverSize { get; set; }

        public decimal MMBatchProductItemProductWidth { get; set; }

        public decimal MMBatchProductItemProductLength { get; set; }

        public decimal MMBatchProductItemProductHeight { get; set; }

        public String ICProductImageFile { get; set; }

        public String ICProductAttributeQuality { get; set; }

        public String ICProductAttributeSpeciality { get; set; }

        public bool HasComponent { get; set; }

        public String MMBatchProductProductionNormItemOverallSize { get; set; }

        public String MMBatchProductItemProductNoOfOldSys { get; set; }
        public decimal MMBatchProductItemOutSourcingProductQty { get; set; }
        public decimal MMBatchProductProductionNormItemNeedMakeQty { get; set; }
        public int MMBatchProductProductionNormItemPaintViscosity { get; set; }
        public string MMBatchProductProductionNormItemPaintExecuteMethod { get; set; }
        public string ARProductionPlanningItemProductRemark { get; set; }
        public string MMBatchProductProductionNormItemMeterialDesc { get; set; }
        public string MMBatchProductProductionNormItemMeterialNo { get; set; }
        public string MMBatchProductProductionNormItemMeterialMeasureUnitName { get; set; }
        #endregion
    }
    #endregion
}