using BOSLib;
using System;
namespace BOSERP
{
    #region MMBatchProductPlanHWs
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MMBatchProductPlanHWsInfo
    //Created Date:Thursday, November 05, 2015
    //-----------------------------------------------------------

    public class MMBatchProductPlanHWsInfo : BusinessObject
    {
        public MMBatchProductPlanHWsInfo()
        {
        }
        #region Variables
        protected int _mMBatchProductPlanHWID;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_MMBatchProductPlanID;
        protected int _fK_ICProductID;
        protected int _fK_ICMeasureUnitID;
        protected String _mMBatchProductPlanHWName = String.Empty;
        protected String _mMBatchProductPlanHWUnit = String.Empty;
        protected double _mMBatchProductPlanHWAssembleOrPackQuantity;
        protected double _mMBatchProductPlanHWAssembleTotalQuantity;
        protected double _mMBatchProductPlanHWAllocationTotalQuantity;
        protected double _mMBatchProductPlanHWBuyTotalQuantity;
        protected DateTime _mMBatchProductPlanHWNeededTime = DateTime.MaxValue;
        protected String _mMBatchProductPlanHWNote = String.Empty;
        protected String _mMBatchProductPlanHWICDepartmentAttribute1 = String.Empty;
        protected String _mMBatchProductPlanHWICDepartmentAttribute2 = String.Empty;
        protected String _mMBatchProductPlanHWICDepartmentAttribute3 = String.Empty;
        protected String _mMBatchProductPlanHWICDepartmentAttribute4 = String.Empty;
        protected String _mMBatchProductPlanHWICDepartmentAttribute5 = String.Empty;
        protected String _mMBatchProductPlanHWICDepartmentAttribute6 = String.Empty;
        protected String _mMBatchProductPlanHWICDepartmentAttribute7 = String.Empty;
        protected String _mMBatchProductPlanHWICDepartmentAttribute8 = String.Empty;
        protected String _mMBatchProductPlanHWICDepartmentAttribute9 = String.Empty;
        protected String _mMBatchProductPlanHWICDepartmentAttribute10 = String.Empty;
        protected String _mMBatchProductPlanHWNo = String.Empty;
        protected String _mMBatchProductPlanHWDesc = String.Empty;
        protected String _mMBatchProductPlanHWPriority = String.Empty;
        protected double _mMBatchProductPlanHWQuantity;
        protected double _mMBatchProductPlanHWInventoryStockQuantity;
        protected double _mMBatchProductPlanHWBoughtQuantity;
        protected String _mMBatchProductPlanHWProposalStatus = DefaultStatus;
        protected double _mMBatchProductPlanPurchaseOrderQty;
        protected double _mMBatchProductPlanReceiptQty;
        protected String _mMBatchProductPlanHWActionType = String.Empty;
        protected String _mMBatchProductPlanHWOldValue = String.Empty;
        protected String _mMBatchProductPlanHWNewValue = String.Empty;
        protected bool _mMBatchProductPlanHWIsChangeBOM = true;
        #endregion

        #region Public properties
        public int MMBatchProductPlanHWID
        {
            get { return _mMBatchProductPlanHWID; }
            set
            {
                if (value != this._mMBatchProductPlanHWID)
                {
                    _mMBatchProductPlanHWID = value;
                    NotifyChanged("MMBatchProductPlanHWID");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_MMBatchProductPlanID
        {
            get { return _fK_MMBatchProductPlanID; }
            set
            {
                if (value != this._fK_MMBatchProductPlanID)
                {
                    _fK_MMBatchProductPlanID = value;
                    NotifyChanged("FK_MMBatchProductPlanID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICMeasureUnitID
        {
            get { return _fK_ICMeasureUnitID; }
            set
            {
                if (value != this._fK_ICMeasureUnitID)
                {
                    _fK_ICMeasureUnitID = value;
                    NotifyChanged("FK_ICMeasureUnitID");
                }
            }
        }
        public String MMBatchProductPlanHWName
        {
            get { return _mMBatchProductPlanHWName; }
            set
            {
                if (value != this._mMBatchProductPlanHWName)
                {
                    _mMBatchProductPlanHWName = value;
                    NotifyChanged("MMBatchProductPlanHWName");
                }
            }
        }
        public String MMBatchProductPlanHWUnit
        {
            get { return _mMBatchProductPlanHWUnit; }
            set
            {
                if (value != this._mMBatchProductPlanHWUnit)
                {
                    _mMBatchProductPlanHWUnit = value;
                    NotifyChanged("MMBatchProductPlanHWUnit");
                }
            }
        }
        public double MMBatchProductPlanHWAssembleOrPackQuantity
        {
            get { return _mMBatchProductPlanHWAssembleOrPackQuantity; }
            set
            {
                if (value != this._mMBatchProductPlanHWAssembleOrPackQuantity)
                {
                    _mMBatchProductPlanHWAssembleOrPackQuantity = value;
                    NotifyChanged("MMBatchProductPlanHWAssembleOrPackQuantity");
                }
            }
        }
        public double MMBatchProductPlanHWAssembleTotalQuantity
        {
            get { return _mMBatchProductPlanHWAssembleTotalQuantity; }
            set
            {
                if (value != this._mMBatchProductPlanHWAssembleTotalQuantity)
                {
                    _mMBatchProductPlanHWAssembleTotalQuantity = value;
                    NotifyChanged("MMBatchProductPlanHWAssembleTotalQuantity");
                }
            }
        }
        public double MMBatchProductPlanHWAllocationTotalQuantity
        {
            get { return _mMBatchProductPlanHWAllocationTotalQuantity; }
            set
            {
                if (value != this._mMBatchProductPlanHWAllocationTotalQuantity)
                {
                    _mMBatchProductPlanHWAllocationTotalQuantity = value;
                    NotifyChanged("MMBatchProductPlanHWAllocationTotalQuantity");
                }
            }
        }
        public double MMBatchProductPlanHWBuyTotalQuantity
        {
            get { return _mMBatchProductPlanHWBuyTotalQuantity; }
            set
            {
                if (value != this._mMBatchProductPlanHWBuyTotalQuantity)
                {
                    _mMBatchProductPlanHWBuyTotalQuantity = value;
                    NotifyChanged("MMBatchProductPlanHWBuyTotalQuantity");
                }
            }
        }
        public DateTime MMBatchProductPlanHWNeededTime
        {
            get { return _mMBatchProductPlanHWNeededTime; }
            set
            {
                if (value != this._mMBatchProductPlanHWNeededTime)
                {
                    _mMBatchProductPlanHWNeededTime = value;
                    NotifyChanged("MMBatchProductPlanHWNeededTime");
                }
            }
        }
        public String MMBatchProductPlanHWNote
        {
            get { return _mMBatchProductPlanHWNote; }
            set
            {
                if (value != this._mMBatchProductPlanHWNote)
                {
                    _mMBatchProductPlanHWNote = value;
                    NotifyChanged("MMBatchProductPlanHWNote");
                }
            }
        }
        public String MMBatchProductPlanHWICDepartmentAttribute1
        {
            get { return _mMBatchProductPlanHWICDepartmentAttribute1; }
            set
            {
                if (value != this._mMBatchProductPlanHWICDepartmentAttribute1)
                {
                    _mMBatchProductPlanHWICDepartmentAttribute1 = value;
                    NotifyChanged("MMBatchProductPlanHWICDepartmentAttribute1");
                }
            }
        }
        public String MMBatchProductPlanHWICDepartmentAttribute2
        {
            get { return _mMBatchProductPlanHWICDepartmentAttribute2; }
            set
            {
                if (value != this._mMBatchProductPlanHWICDepartmentAttribute2)
                {
                    _mMBatchProductPlanHWICDepartmentAttribute2 = value;
                    NotifyChanged("MMBatchProductPlanHWICDepartmentAttribute2");
                }
            }
        }
        public String MMBatchProductPlanHWICDepartmentAttribute3
        {
            get { return _mMBatchProductPlanHWICDepartmentAttribute3; }
            set
            {
                if (value != this._mMBatchProductPlanHWICDepartmentAttribute3)
                {
                    _mMBatchProductPlanHWICDepartmentAttribute3 = value;
                    NotifyChanged("MMBatchProductPlanHWICDepartmentAttribute3");
                }
            }
        }
        public String MMBatchProductPlanHWICDepartmentAttribute4
        {
            get { return _mMBatchProductPlanHWICDepartmentAttribute4; }
            set
            {
                if (value != this._mMBatchProductPlanHWICDepartmentAttribute4)
                {
                    _mMBatchProductPlanHWICDepartmentAttribute4 = value;
                    NotifyChanged("MMBatchProductPlanHWICDepartmentAttribute4");
                }
            }
        }
        public String MMBatchProductPlanHWICDepartmentAttribute5
        {
            get { return _mMBatchProductPlanHWICDepartmentAttribute5; }
            set
            {
                if (value != this._mMBatchProductPlanHWICDepartmentAttribute5)
                {
                    _mMBatchProductPlanHWICDepartmentAttribute5 = value;
                    NotifyChanged("MMBatchProductPlanHWICDepartmentAttribute5");
                }
            }
        }
        public String MMBatchProductPlanHWICDepartmentAttribute6
        {
            get { return _mMBatchProductPlanHWICDepartmentAttribute6; }
            set
            {
                if (value != this._mMBatchProductPlanHWICDepartmentAttribute6)
                {
                    _mMBatchProductPlanHWICDepartmentAttribute6 = value;
                    NotifyChanged("MMBatchProductPlanHWICDepartmentAttribute6");
                }
            }
        }
        public String MMBatchProductPlanHWICDepartmentAttribute7
        {
            get { return _mMBatchProductPlanHWICDepartmentAttribute7; }
            set
            {
                if (value != this._mMBatchProductPlanHWICDepartmentAttribute7)
                {
                    _mMBatchProductPlanHWICDepartmentAttribute7 = value;
                    NotifyChanged("MMBatchProductPlanHWICDepartmentAttribute7");
                }
            }
        }
        public String MMBatchProductPlanHWICDepartmentAttribute8
        {
            get { return _mMBatchProductPlanHWICDepartmentAttribute8; }
            set
            {
                if (value != this._mMBatchProductPlanHWICDepartmentAttribute8)
                {
                    _mMBatchProductPlanHWICDepartmentAttribute8 = value;
                    NotifyChanged("MMBatchProductPlanHWICDepartmentAttribute8");
                }
            }
        }
        public String MMBatchProductPlanHWICDepartmentAttribute9
        {
            get { return _mMBatchProductPlanHWICDepartmentAttribute9; }
            set
            {
                if (value != this._mMBatchProductPlanHWICDepartmentAttribute9)
                {
                    _mMBatchProductPlanHWICDepartmentAttribute9 = value;
                    NotifyChanged("MMBatchProductPlanHWICDepartmentAttribute9");
                }
            }
        }
        public String MMBatchProductPlanHWICDepartmentAttribute10
        {
            get { return _mMBatchProductPlanHWICDepartmentAttribute10; }
            set
            {
                if (value != this._mMBatchProductPlanHWICDepartmentAttribute10)
                {
                    _mMBatchProductPlanHWICDepartmentAttribute10 = value;
                    NotifyChanged("MMBatchProductPlanHWICDepartmentAttribute10");
                }
            }
        }
        public String MMBatchProductPlanHWNo
        {
            get { return _mMBatchProductPlanHWNo; }
            set
            {
                if (value != this._mMBatchProductPlanHWNo)
                {
                    _mMBatchProductPlanHWNo = value;
                    NotifyChanged("MMBatchProductPlanHWNo");
                }
            }
        }
        public String MMBatchProductPlanHWDesc
        {
            get { return _mMBatchProductPlanHWDesc; }
            set
            {
                if (value != this._mMBatchProductPlanHWDesc)
                {
                    _mMBatchProductPlanHWDesc = value;
                    NotifyChanged("MMBatchProductPlanHWDesc");
                }
            }
        }
        public String MMBatchProductPlanHWPriority
        {
            get { return _mMBatchProductPlanHWPriority; }
            set
            {
                if (value != this._mMBatchProductPlanHWPriority)
                {
                    _mMBatchProductPlanHWPriority = value;
                    NotifyChanged("MMBatchProductPlanHWPriority");
                }
            }
        }
        public double MMBatchProductPlanHWQuantity
        {
            get { return _mMBatchProductPlanHWQuantity; }
            set
            {
                if (value != this._mMBatchProductPlanHWQuantity)
                {
                    _mMBatchProductPlanHWQuantity = value;
                    NotifyChanged("MMBatchProductPlanHWQuantity");
                }
            }
        }
        public double MMBatchProductPlanHWInventoryStockQuantity
        {
            get { return _mMBatchProductPlanHWInventoryStockQuantity; }
            set
            {
                if (value != this._mMBatchProductPlanHWInventoryStockQuantity)
                {
                    _mMBatchProductPlanHWInventoryStockQuantity = value;
                    NotifyChanged("MMBatchProductPlanHWInventoryStockQuantity");
                }
            }
        }
        public double MMBatchProductPlanHWBoughtQuantity
        {
            get { return _mMBatchProductPlanHWBoughtQuantity; }
            set
            {
                if (value != this._mMBatchProductPlanHWBoughtQuantity)
                {
                    _mMBatchProductPlanHWBoughtQuantity = value;
                    NotifyChanged("MMBatchProductPlanHWBoughtQuantity");
                }
            }
        }
        public String MMBatchProductPlanHWProposalStatus
        {
            get { return _mMBatchProductPlanHWProposalStatus; }
            set
            {
                if (value != this._mMBatchProductPlanHWProposalStatus)
                {
                    _mMBatchProductPlanHWProposalStatus = value;
                    NotifyChanged("MMBatchProductPlanHWProposalStatus");
                }
            }
        }
        public double MMBatchProductPlanPurchaseOrderQty
        {
            get { return _mMBatchProductPlanPurchaseOrderQty; }
            set
            {
                if (value != this._mMBatchProductPlanPurchaseOrderQty)
                {
                    _mMBatchProductPlanPurchaseOrderQty = value;
                    NotifyChanged("MMBatchProductPlanPurchaseOrderQty");
                }
            }
        }
        public double MMBatchProductPlanReceiptQty
        {
            get { return _mMBatchProductPlanReceiptQty; }
            set
            {
                if (value != this._mMBatchProductPlanReceiptQty)
                {
                    _mMBatchProductPlanReceiptQty = value;
                    NotifyChanged("MMBatchProductPlanReceiptQty");
                }
            }
        }
        public String MMBatchProductPlanHWActionType
        {
            get { return _mMBatchProductPlanHWActionType; }
            set
            {
                if (value != this._mMBatchProductPlanHWActionType)
                {
                    _mMBatchProductPlanHWActionType = value;
                    NotifyChanged("MMBatchProductPlanHWActionType");
                }
            }
        }
        public String MMBatchProductPlanHWOldValue
        {
            get { return _mMBatchProductPlanHWOldValue; }
            set
            {
                if (value != this._mMBatchProductPlanHWOldValue)
                {
                    _mMBatchProductPlanHWOldValue = value;
                    NotifyChanged("MMBatchProductPlanHWOldValue");
                }
            }
        }
        public String MMBatchProductPlanHWNewValue
        {
            get { return _mMBatchProductPlanHWNewValue; }
            set
            {
                if (value != this._mMBatchProductPlanHWNewValue)
                {
                    _mMBatchProductPlanHWNewValue = value;
                    NotifyChanged("MMBatchProductPlanHWNewValue");
                }
            }
        }
        public bool MMBatchProductPlanHWIsChangeBOM
        {
            get { return _mMBatchProductPlanHWIsChangeBOM; }
            set
            {
                if (value != this._mMBatchProductPlanHWIsChangeBOM)
                {
                    _mMBatchProductPlanHWIsChangeBOM = value;
                    NotifyChanged("MMBatchProductPlanHWIsChangeBOM");
                }
            }
        }
        #endregion
    }
    #endregion
}