using BOSLib;
using System;
namespace BOSERP
{
    #region MMDepartmentAndOperations
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MMDepartmentAndOperationsInfo
    //Created Date:Friday, April 12, 2019
    //-----------------------------------------------------------

    public class MMDepartmentAndOperationsInfo : BusinessObject
    {
        public MMDepartmentAndOperationsInfo()
        {
        }
        #region Variables
        protected int _mMDepartmentAndOperationID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_HRDepartmentID;
        protected int _fK_MMOperationID;
        protected int _fK_MMWorkShopID;
        #endregion

        #region Public properties
        public int MMDepartmentAndOperationID
        {
            get { return _mMDepartmentAndOperationID; }
            set
            {
                if (value != this._mMDepartmentAndOperationID)
                {
                    _mMDepartmentAndOperationID = value;
                    NotifyChanged("MMDepartmentAndOperationID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_HRDepartmentID
        {
            get { return _fK_HRDepartmentID; }
            set
            {
                if (value != this._fK_HRDepartmentID)
                {
                    _fK_HRDepartmentID = value;
                    NotifyChanged("FK_HRDepartmentID");
                }
            }
        }
        public int FK_MMOperationID
        {
            get { return _fK_MMOperationID; }
            set
            {
                if (value != this._fK_MMOperationID)
                {
                    _fK_MMOperationID = value;
                    NotifyChanged("FK_MMOperationID");
                }
            }
        }
        public int FK_MMWorkShopID
        {
            get { return _fK_MMWorkShopID; }
            set
            {
                if (value != this._fK_MMWorkShopID)
                {
                    _fK_MMWorkShopID = value;
                    NotifyChanged("FK_MMWorkShopID");
                }
            }
        }
        #endregion

    }
    #endregion
}