using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
	#region MMFalseConditionalItems
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:MMFalseConditionalItemsInfo
	//Created Date:21/02/2024 10:36:35 AM
	//-----------------------------------------------------------

	public class MMFalseConditionalItemsInfo : BusinessObject
	{
		public MMFalseConditionalItemsInfo()
		{
		}
		#region Variables
		protected int _mMFalseConditionalItemID;
		protected string _aAStatus = DefaultAAStatus;
		protected string _aACreatedUser = string.Empty;
		protected DateTime _aACreatedDate = DateTime.MaxValue;
		protected string _aAUpdatedUser = string.Empty;
		protected DateTime _aAUpdatedDate = DateTime.MaxValue;
		protected int _fK_ICProductSerieID;
		protected int _fK_ICProductAttributeQualityID;
		protected string _mMFalseConditionalItemHumidity = string.Empty;
		protected decimal _mMFalseConditionalItemProductLength;
		protected decimal _mMFalseConditionalItemProductWidth;
		protected decimal _mMFalseConditionalItemProductHeight;
		protected decimal _mMFalseConditionalItemWoodQty;
		protected decimal _mMFalseConditionalItemInventoryWoodQty;
		protected decimal _mMFalseConditionalItemFaultPercent;
		protected decimal _mMFalseConditionalItemGoodPercent;
		protected string _mMFalseConditionalItemResult = string.Empty;
		protected string _mMFalseConditionalItemComment = string.Empty;
		protected string _mMFalseConditionalItemProductSerialNo = string.Empty;
		protected int _fK_MMFalseConditionalID;
		protected string _mMFalseConditionalItemProductAttributeQuality = string.Empty;
		#endregion

		#region Public properties
		public int MMFalseConditionalItemID
		{
			get { return _mMFalseConditionalItemID; }
			set
			{
				if (value != this._mMFalseConditionalItemID)
				{
					_mMFalseConditionalItemID = value;
					NotifyChanged("MMFalseConditionalItemID");
				}
			}
		}
		public string AAStatus
		{
			get { return _aAStatus; }
			set
			{
				if (value != this._aAStatus)
				{
					_aAStatus = value;
					NotifyChanged("AAStatus");
				}
			}
		}
		public string AACreatedUser
		{
			get { return _aACreatedUser; }
			set
			{
				if (value != this._aACreatedUser)
				{
					_aACreatedUser = value;
					NotifyChanged("AACreatedUser");
				}
			}
		}
		public DateTime AACreatedDate
		{
			get { return _aACreatedDate; }
			set
			{
				if (value != this._aACreatedDate)
				{
					_aACreatedDate = value;
					NotifyChanged("AACreatedDate");
				}
			}
		}
		public string AAUpdatedUser
		{
			get { return _aAUpdatedUser; }
			set
			{
				if (value != this._aAUpdatedUser)
				{
					_aAUpdatedUser = value;
					NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public DateTime AAUpdatedDate
		{
			get { return _aAUpdatedDate; }
			set
			{
				if (value != this._aAUpdatedDate)
				{
					_aAUpdatedDate = value;
					NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public int FK_ICProductSerieID
		{
			get { return _fK_ICProductSerieID; }
			set
			{
				if (value != this._fK_ICProductSerieID)
				{
					_fK_ICProductSerieID = value;
					NotifyChanged("FK_ICProductSerieID");
				}
			}
		}
		public int FK_ICProductAttributeQualityID
		{
			get { return _fK_ICProductAttributeQualityID; }
			set
			{
				if (value != this._fK_ICProductAttributeQualityID)
				{
					_fK_ICProductAttributeQualityID = value;
					NotifyChanged("FK_ICProductAttributeQualityID");
				}
			}
		}
		public string MMFalseConditionalItemHumidity
		{
			get { return _mMFalseConditionalItemHumidity; }
			set
			{
				if (value != this._mMFalseConditionalItemHumidity)
				{
					_mMFalseConditionalItemHumidity = value;
					NotifyChanged("MMFalseConditionalItemHumidity");
				}
			}
		}
		public decimal MMFalseConditionalItemProductLength
		{
			get { return _mMFalseConditionalItemProductLength; }
			set
			{
				if (value != this._mMFalseConditionalItemProductLength)
				{
					_mMFalseConditionalItemProductLength = value;
					NotifyChanged("MMFalseConditionalItemProductLength");
				}
			}
		}
		public decimal MMFalseConditionalItemProductWidth
		{
			get { return _mMFalseConditionalItemProductWidth; }
			set
			{
				if (value != this._mMFalseConditionalItemProductWidth)
				{
					_mMFalseConditionalItemProductWidth = value;
					NotifyChanged("MMFalseConditionalItemProductWidth");
				}
			}
		}
		public decimal MMFalseConditionalItemProductHeight
		{
			get { return _mMFalseConditionalItemProductHeight; }
			set
			{
				if (value != this._mMFalseConditionalItemProductHeight)
				{
					_mMFalseConditionalItemProductHeight = value;
					NotifyChanged("MMFalseConditionalItemProductHeight");
				}
			}
		}
		public decimal MMFalseConditionalItemWoodQty
		{
			get { return _mMFalseConditionalItemWoodQty; }
			set
			{
				if (value != this._mMFalseConditionalItemWoodQty)
				{
					_mMFalseConditionalItemWoodQty = value;
					NotifyChanged("MMFalseConditionalItemWoodQty");
				}
			}
		}
		public decimal MMFalseConditionalItemInventoryWoodQty
		{
			get { return _mMFalseConditionalItemInventoryWoodQty; }
			set
			{
				if (value != this._mMFalseConditionalItemInventoryWoodQty)
				{
					_mMFalseConditionalItemInventoryWoodQty = value;
					NotifyChanged("MMFalseConditionalItemInventoryWoodQty");
				}
			}
		}
		public decimal MMFalseConditionalItemFaultPercent
		{
			get { return _mMFalseConditionalItemFaultPercent; }
			set
			{
				if (value != this._mMFalseConditionalItemFaultPercent)
				{
					_mMFalseConditionalItemFaultPercent = value;
					NotifyChanged("MMFalseConditionalItemFaultPercent");
				}
			}
		}
		public decimal MMFalseConditionalItemGoodPercent
		{
			get { return _mMFalseConditionalItemGoodPercent; }
			set
			{
				if (value != this._mMFalseConditionalItemGoodPercent)
				{
					_mMFalseConditionalItemGoodPercent = value;
					NotifyChanged("MMFalseConditionalItemGoodPercent");
				}
			}
		}
		public string MMFalseConditionalItemResult
		{
			get { return _mMFalseConditionalItemResult; }
			set
			{
				if (value != this._mMFalseConditionalItemResult)
				{
					_mMFalseConditionalItemResult = value;
					NotifyChanged("MMFalseConditionalItemResult");
				}
			}
		}
		public string MMFalseConditionalItemComment
		{
			get { return _mMFalseConditionalItemComment; }
			set
			{
				if (value != this._mMFalseConditionalItemComment)
				{
					_mMFalseConditionalItemComment = value;
					NotifyChanged("MMFalseConditionalItemComment");
				}
			}
		}
		public string MMFalseConditionalItemProductSerialNo
		{
			get { return _mMFalseConditionalItemProductSerialNo; }
			set
			{
				if (value != this._mMFalseConditionalItemProductSerialNo)
				{
					_mMFalseConditionalItemProductSerialNo = value;
					NotifyChanged("MMFalseConditionalItemProductSerialNo");
				}
			}
		}
		public int FK_MMFalseConditionalID
		{
			get { return _fK_MMFalseConditionalID; }
			set
			{
				if (value != this._fK_MMFalseConditionalID)
				{
					_fK_MMFalseConditionalID = value;
					NotifyChanged("FK_MMFalseConditionalID");
				}
			}
		}
		public string MMFalseConditionalItemProductAttributeQuality
		{
			get { return _mMFalseConditionalItemProductAttributeQuality; }
			set
			{
				if (value != this._mMFalseConditionalItemProductAttributeQuality)
				{
					_mMFalseConditionalItemProductAttributeQuality = value;
					NotifyChanged("MMFalseConditionalItemProductAttributeQuality");
				}
			}
		}
        #endregion
        #region Extra Properties
		public IBOSList<MMFalseConditionalDetailsInfo> MMFalseConditionalDetailList { get; set; }
		public decimal MMFalseConditionalItemTotalPercent { get; set; }
		public decimal MMFalseConditionalItemHardPercent { get; set; }
		public decimal MMFalseConditionalItemSoftPercent { get; set; }
        #endregion
    }
    #endregion
}