using BOSLib;
using System;
namespace BOSERP
{
    #region MMOperationMachineGroups
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MMOperationMachineGroupsInfo
    //Created Date:Thursday, January 17, 2019
    //-----------------------------------------------------------

    public class MMOperationMachineGroupsInfo : BusinessObject
    {
        public MMOperationMachineGroupsInfo()
        {
            MMOperationMachineGroupIsDefault = false;
        }
        #region Variables
        protected int _mMOperationMachineGroupID;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_MMOperationID;
        protected String _mMMachineGroup = String.Empty;
        protected bool _mMOperationMachineGroupIsDefault = true;
        #endregion

        #region Public properties
        public int MMOperationMachineGroupID
        {
            get { return _mMOperationMachineGroupID; }
            set
            {
                if (value != this._mMOperationMachineGroupID)
                {
                    _mMOperationMachineGroupID = value;
                    NotifyChanged("MMOperationMachineGroupID");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_MMOperationID
        {
            get { return _fK_MMOperationID; }
            set
            {
                if (value != this._fK_MMOperationID)
                {
                    _fK_MMOperationID = value;
                    NotifyChanged("FK_MMOperationID");
                }
            }
        }
        public String MMMachineGroup
        {
            get { return _mMMachineGroup; }
            set
            {
                if (value != this._mMMachineGroup)
                {
                    _mMMachineGroup = value;
                    NotifyChanged("MMMachineGroup");
                }
            }
        }
        public bool MMOperationMachineGroupIsDefault
        {
            get { return _mMOperationMachineGroupIsDefault; }
            set
            {
                if (value != this._mMOperationMachineGroupIsDefault)
                {
                    _mMOperationMachineGroupIsDefault = value;
                    NotifyChanged("MMOperationMachineGroupIsDefault");
                }
            }
        }
        #endregion
    }
    #endregion
}