using BOSLib;
using System;
namespace BOSERP
{
    #region ARAdjustSaleOrderQuantityItems
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ARAdjustSaleOrderQuantityItemsInfo
    //Created Date:Friday, July 08, 2016
    //-----------------------------------------------------------

    public class ARAdjustSaleOrderQuantityItemsInfo : BusinessObject
    {
        public ARAdjustSaleOrderQuantityItemsInfo()
        {
        }
        #region Variables
        protected int _aRAdjustSaleOrderQuantityItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ARAdjustSaleOrderQuantityID;
        protected int _fK_ICDepartmentID;
        protected int _fK_ICProductGroupID;
        protected int _fK_ICProductID;
        protected int _fK_ICMeasureUnitID;
        protected int _fK_ICStockID;
        protected int _fK_ARSaleOrderID;
        protected int _fK_ARSaleOrderItemID;
        protected String _aRAdjustSaleOrderQuantityItemProductType = String.Empty;
        protected String _aRAdjustSaleOrderQuantityItemProductSerialNo = String.Empty;
        protected String _aRAdjustSaleOrderQuantityItemProductAttribute = String.Empty;
        protected String _aRAdjustSaleOrderQuantityItemProductName = String.Empty;
        protected String _aRAdjustSaleOrderQuantityItemProductDesc = String.Empty;
        protected decimal _aRAdjustSaleOrderQuantityItemProductUnitPrice;
        protected decimal _aRAdjustSaleOrderQuantityItemProductUnitCost;
        protected decimal _aRAdjustSaleOrderQuantityItemProductDiscount;
        protected decimal _aRAdjustSaleOrderQuantityItemProductTaxPercent;
        protected decimal _aRAdjustSaleOrderQuantityItemProductQty;
        protected decimal _aRAdjustSaleOrderQuantityItemOrderedQty;
        protected decimal _aRAdjustSaleOrderQuantityItemTotalQty;
        protected decimal _aRAdjustSaleOrderQuantityItemPrice;
        protected decimal _aRAdjustSaleOrderQuantityItemTaxAmount;
        protected decimal _aRAdjustSaleOrderQuantityItemDiscountAmount;
        protected decimal _aRAdjustSaleOrderQuantityItemNetAmount;
        protected decimal _aRAdjustSaleOrderQuantityItemTotalAmount;
        protected decimal _aRAdjustSaleOrderQuantityItemTotalCost;
        protected String _aRAdjustSaleOrderQuantityItemProductSupplierNo = String.Empty;
        protected String _aRAdjustSaleOrderQuantityItemComment = String.Empty;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected decimal _aRAdjustSaleOrderQuantityItemProductOldQty;
        #endregion

        #region Public properties
        public int ARAdjustSaleOrderQuantityItemID
        {
            get { return _aRAdjustSaleOrderQuantityItemID; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemID)
                {
                    _aRAdjustSaleOrderQuantityItemID = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_ARAdjustSaleOrderQuantityID
        {
            get { return _fK_ARAdjustSaleOrderQuantityID; }
            set
            {
                if (value != this._fK_ARAdjustSaleOrderQuantityID)
                {
                    _fK_ARAdjustSaleOrderQuantityID = value;
                    NotifyChanged("FK_ARAdjustSaleOrderQuantityID");
                }
            }
        }
        public int FK_ICDepartmentID
        {
            get { return _fK_ICDepartmentID; }
            set
            {
                if (value != this._fK_ICDepartmentID)
                {
                    _fK_ICDepartmentID = value;
                    NotifyChanged("FK_ICDepartmentID");
                }
            }
        }
        public int FK_ICProductGroupID
        {
            get { return _fK_ICProductGroupID; }
            set
            {
                if (value != this._fK_ICProductGroupID)
                {
                    _fK_ICProductGroupID = value;
                    NotifyChanged("FK_ICProductGroupID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICMeasureUnitID
        {
            get { return _fK_ICMeasureUnitID; }
            set
            {
                if (value != this._fK_ICMeasureUnitID)
                {
                    _fK_ICMeasureUnitID = value;
                    NotifyChanged("FK_ICMeasureUnitID");
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                    NotifyChanged("FK_ICStockID");
                }
            }
        }
        public int FK_ARSaleOrderID
        {
            get { return _fK_ARSaleOrderID; }
            set
            {
                if (value != this._fK_ARSaleOrderID)
                {
                    _fK_ARSaleOrderID = value;
                    NotifyChanged("FK_ARSaleOrderID");
                }
            }
        }
        public int FK_ARSaleOrderItemID
        {
            get { return _fK_ARSaleOrderItemID; }
            set
            {
                if (value != this._fK_ARSaleOrderItemID)
                {
                    _fK_ARSaleOrderItemID = value;
                    NotifyChanged("FK_ARSaleOrderItemID");
                }
            }
        }
        public String ARAdjustSaleOrderQuantityItemProductType
        {
            get { return _aRAdjustSaleOrderQuantityItemProductType; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductType)
                {
                    _aRAdjustSaleOrderQuantityItemProductType = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductType");
                }
            }
        }
        public String ARAdjustSaleOrderQuantityItemProductSerialNo
        {
            get { return _aRAdjustSaleOrderQuantityItemProductSerialNo; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductSerialNo)
                {
                    _aRAdjustSaleOrderQuantityItemProductSerialNo = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductSerialNo");
                }
            }
        }
        public String ARAdjustSaleOrderQuantityItemProductAttribute
        {
            get { return _aRAdjustSaleOrderQuantityItemProductAttribute; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductAttribute)
                {
                    _aRAdjustSaleOrderQuantityItemProductAttribute = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductAttribute");
                }
            }
        }
        public String ARAdjustSaleOrderQuantityItemProductName
        {
            get { return _aRAdjustSaleOrderQuantityItemProductName; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductName)
                {
                    _aRAdjustSaleOrderQuantityItemProductName = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductName");
                }
            }
        }
        public String ARAdjustSaleOrderQuantityItemProductDesc
        {
            get { return _aRAdjustSaleOrderQuantityItemProductDesc; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductDesc)
                {
                    _aRAdjustSaleOrderQuantityItemProductDesc = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductDesc");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemProductUnitPrice
        {
            get { return _aRAdjustSaleOrderQuantityItemProductUnitPrice; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductUnitPrice)
                {
                    _aRAdjustSaleOrderQuantityItemProductUnitPrice = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductUnitPrice");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemProductUnitCost
        {
            get { return _aRAdjustSaleOrderQuantityItemProductUnitCost; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductUnitCost)
                {
                    _aRAdjustSaleOrderQuantityItemProductUnitCost = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductUnitCost");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemProductDiscount
        {
            get { return _aRAdjustSaleOrderQuantityItemProductDiscount; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductDiscount)
                {
                    _aRAdjustSaleOrderQuantityItemProductDiscount = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductDiscount");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemProductTaxPercent
        {
            get { return _aRAdjustSaleOrderQuantityItemProductTaxPercent; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductTaxPercent)
                {
                    _aRAdjustSaleOrderQuantityItemProductTaxPercent = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductTaxPercent");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemProductQty
        {
            get { return _aRAdjustSaleOrderQuantityItemProductQty; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductQty)
                {
                    _aRAdjustSaleOrderQuantityItemProductQty = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductQty");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemOrderedQty
        {
            get { return _aRAdjustSaleOrderQuantityItemOrderedQty; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemOrderedQty)
                {
                    _aRAdjustSaleOrderQuantityItemOrderedQty = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemOrderedQty");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemTotalQty
        {
            get { return _aRAdjustSaleOrderQuantityItemTotalQty; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemTotalQty)
                {
                    _aRAdjustSaleOrderQuantityItemTotalQty = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemTotalQty");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemPrice
        {
            get { return _aRAdjustSaleOrderQuantityItemPrice; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemPrice)
                {
                    _aRAdjustSaleOrderQuantityItemPrice = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemPrice");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemTaxAmount
        {
            get { return _aRAdjustSaleOrderQuantityItemTaxAmount; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemTaxAmount)
                {
                    _aRAdjustSaleOrderQuantityItemTaxAmount = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemTaxAmount");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemDiscountAmount
        {
            get { return _aRAdjustSaleOrderQuantityItemDiscountAmount; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemDiscountAmount)
                {
                    _aRAdjustSaleOrderQuantityItemDiscountAmount = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemDiscountAmount");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemNetAmount
        {
            get { return _aRAdjustSaleOrderQuantityItemNetAmount; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemNetAmount)
                {
                    _aRAdjustSaleOrderQuantityItemNetAmount = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemNetAmount");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemTotalAmount
        {
            get { return _aRAdjustSaleOrderQuantityItemTotalAmount; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemTotalAmount)
                {
                    _aRAdjustSaleOrderQuantityItemTotalAmount = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemTotalAmount");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemTotalCost
        {
            get { return _aRAdjustSaleOrderQuantityItemTotalCost; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemTotalCost)
                {
                    _aRAdjustSaleOrderQuantityItemTotalCost = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemTotalCost");
                }
            }
        }
        public String ARAdjustSaleOrderQuantityItemProductSupplierNo
        {
            get { return _aRAdjustSaleOrderQuantityItemProductSupplierNo; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductSupplierNo)
                {
                    _aRAdjustSaleOrderQuantityItemProductSupplierNo = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductSupplierNo");
                }
            }
        }
        public String ARAdjustSaleOrderQuantityItemComment
        {
            get { return _aRAdjustSaleOrderQuantityItemComment; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemComment)
                {
                    _aRAdjustSaleOrderQuantityItemComment = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemComment");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public decimal ARAdjustSaleOrderQuantityItemProductOldQty
        {
            get { return _aRAdjustSaleOrderQuantityItemProductOldQty; }
            set
            {
                if (value != this._aRAdjustSaleOrderQuantityItemProductOldQty)
                {
                    _aRAdjustSaleOrderQuantityItemProductOldQty = value;
                    NotifyChanged("ARAdjustSaleOrderQuantityItemProductOldQty");
                }
            }
        }
        #endregion
    }
    #endregion
}