using BOSLib;
using System;
namespace BOSERP
{
    #region ARCustomerPaymentDetails
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ARCustomerPaymentDetailsInfo
    //Created Date:Tuesday, January 17, 2012
    //-----------------------------------------------------------

    public class ARCustomerPaymentDetailsInfo : BusinessObject
    {
        public ARCustomerPaymentDetailsInfo()
        {
        }
        #region Variables
        protected int _aRCustomerPaymentDetailID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ARCustomerPaymentID;
        protected String _aRPaymentMethodCombo = String.Empty;
        protected decimal _aRCustomerPaymentDetailAmount;
        protected String _aRCustomerPaymentDetailInfo = String.Empty;
        protected decimal _aRCustomerPaymentDetailSubAmount1;
        protected decimal _aRCustomerPaymentDetailSubAmount2;
        protected decimal _aRCustomerPaymentDetailSubAmount3;
        protected decimal _aRCustomerPaymentDetailSubAmount4;
        protected decimal _aRCustomerPaymentDetailSubAmount5;
        protected decimal _aRCustomerPaymentDetailSubAmount6;
        protected decimal _aRCustomerPaymentDetailSubAmount7;
        protected decimal _aRCustomerPaymentDetailSubAmount8;
        protected decimal _aRCustomerPaymentDetailSubAmount9;
        protected decimal _aRCustomerPaymentDetailSubAmount10;
        protected decimal _aRCustomerPaymentDetailSubAmount11;
        protected decimal _aRCustomerPaymentDetailSubAmount12;
        protected decimal _aRCustomerPaymentDetailSubAmount13;
        protected decimal _aRCustomerPaymentDetailSubAmount14;
        protected decimal _aRCustomerPaymentDetailSubAmount15;
        protected int _fK_CSCompanyBankID;
        protected int _fK_CSCashFundID;
        #endregion

        #region Public properties
        public int ARCustomerPaymentDetailID
        {
            get { return _aRCustomerPaymentDetailID; }
            set
            {
                if (value != this._aRCustomerPaymentDetailID)
                {
                    _aRCustomerPaymentDetailID = value;
                    NotifyChanged("ARCustomerPaymentDetailID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_ARCustomerPaymentID
        {
            get { return _fK_ARCustomerPaymentID; }
            set
            {
                if (value != this._fK_ARCustomerPaymentID)
                {
                    _fK_ARCustomerPaymentID = value;
                    NotifyChanged("FK_ARCustomerPaymentID");
                }
            }
        }
        public String ARPaymentMethodCombo
        {
            get { return _aRPaymentMethodCombo; }
            set
            {
                if (value != this._aRPaymentMethodCombo)
                {
                    _aRPaymentMethodCombo = value;
                    NotifyChanged("ARPaymentMethodCombo");
                }
            }
        }
        public decimal ARCustomerPaymentDetailAmount
        {
            get { return _aRCustomerPaymentDetailAmount; }
            set
            {
                if (value != this._aRCustomerPaymentDetailAmount)
                {
                    _aRCustomerPaymentDetailAmount = value;
                    NotifyChanged("ARCustomerPaymentDetailAmount");
                }
            }
        }
        public String ARCustomerPaymentDetailInfo
        {
            get { return _aRCustomerPaymentDetailInfo; }
            set
            {
                if (value != this._aRCustomerPaymentDetailInfo)
                {
                    _aRCustomerPaymentDetailInfo = value;
                    NotifyChanged("ARCustomerPaymentDetailInfo");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount1
        {
            get { return _aRCustomerPaymentDetailSubAmount1; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount1)
                {
                    _aRCustomerPaymentDetailSubAmount1 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount1");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount2
        {
            get { return _aRCustomerPaymentDetailSubAmount2; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount2)
                {
                    _aRCustomerPaymentDetailSubAmount2 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount2");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount3
        {
            get { return _aRCustomerPaymentDetailSubAmount3; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount3)
                {
                    _aRCustomerPaymentDetailSubAmount3 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount3");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount4
        {
            get { return _aRCustomerPaymentDetailSubAmount4; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount4)
                {
                    _aRCustomerPaymentDetailSubAmount4 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount4");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount5
        {
            get { return _aRCustomerPaymentDetailSubAmount5; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount5)
                {
                    _aRCustomerPaymentDetailSubAmount5 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount5");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount6
        {
            get { return _aRCustomerPaymentDetailSubAmount6; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount6)
                {
                    _aRCustomerPaymentDetailSubAmount6 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount6");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount7
        {
            get { return _aRCustomerPaymentDetailSubAmount7; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount7)
                {
                    _aRCustomerPaymentDetailSubAmount7 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount7");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount8
        {
            get { return _aRCustomerPaymentDetailSubAmount8; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount8)
                {
                    _aRCustomerPaymentDetailSubAmount8 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount8");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount9
        {
            get { return _aRCustomerPaymentDetailSubAmount9; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount9)
                {
                    _aRCustomerPaymentDetailSubAmount9 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount9");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount10
        {
            get { return _aRCustomerPaymentDetailSubAmount10; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount10)
                {
                    _aRCustomerPaymentDetailSubAmount10 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount10");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount11
        {
            get { return _aRCustomerPaymentDetailSubAmount11; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount11)
                {
                    _aRCustomerPaymentDetailSubAmount11 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount11");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount12
        {
            get { return _aRCustomerPaymentDetailSubAmount12; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount12)
                {
                    _aRCustomerPaymentDetailSubAmount12 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount12");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount13
        {
            get { return _aRCustomerPaymentDetailSubAmount13; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount13)
                {
                    _aRCustomerPaymentDetailSubAmount13 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount13");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount14
        {
            get { return _aRCustomerPaymentDetailSubAmount14; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount14)
                {
                    _aRCustomerPaymentDetailSubAmount14 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount14");
                }
            }
        }
        public decimal ARCustomerPaymentDetailSubAmount15
        {
            get { return _aRCustomerPaymentDetailSubAmount15; }
            set
            {
                if (value != this._aRCustomerPaymentDetailSubAmount15)
                {
                    _aRCustomerPaymentDetailSubAmount15 = value;
                    NotifyChanged("ARCustomerPaymentDetailSubAmount15");
                }
            }
        }

        public int FK_CSCompanyBankID
        {
            get { return _fK_CSCompanyBankID; }
            set
            {
                if (value != this._fK_CSCompanyBankID)
                {
                    _fK_CSCompanyBankID = value;
                    NotifyChanged("FK_CSCompanyBankID");
                }
            }
        }
        public int FK_CSCashFundID
        {
            get { return _fK_CSCashFundID; }
            set
            {
                if (value != this._fK_CSCashFundID)
                {
                    _fK_CSCashFundID = value;
                    NotifyChanged("FK_CSCashFundID");
                }
            }
        }

        #endregion

        #region Extra Properties
        public string ARPaymentMethodDisplayText { get; set; }

        /// <summary>
        /// Gets or sets the list of payments by currencies of a payment details
        /// </summary>
        public IBOSList<ARCustomerPaymentCurrencysInfo> PaymentCurrencys { get; set; }

        public string GECurrencyName { get; set; }

        public decimal ARCustomerPaymentDetailExchangeRate { get; set; }
        #endregion
    }
    #endregion
}