//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShipmentSaleOrderLocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipmentSaleOrderLocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOSERP.Procedure.Modules.IC.ShipmentSaleOrder.Localization.ShipmentSaleOrderLocalizedResour" +
                            "ces", typeof(ShipmentSaleOrderLocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn kho cho từng sản phẩm!.
        /// </summary>
        public static string ChooseStockMessage {
            get {
                return ResourceManager.GetString("ChooseStockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dòng.
        /// </summary>
        public static string ItemCopyNewRow {
            get {
                return ResourceManager.GetString("ItemCopyNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các sản phẩm được chọn phải cùng một đơn bán hàng!.
        /// </summary>
        public static string NewFromDeleveryPlanErrorMessage {
            get {
                return ResourceManager.GetString("NewFromDeleveryPlanErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng xuất kho lớn hơn số lượng đề nghị, số lượng lớn nhất có thể xuất kho là {0}.
        /// </summary>
        public static string QtyMax {
            get {
                return ResourceManager.GetString("QtyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn mã lô!.
        /// </summary>
        public static string SerialProductsIDIsNullMessage {
            get {
                return ResourceManager.GetString("SerialProductsIDIsNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn kho!.
        /// </summary>
        public static string StockIDIsNullMessage {
            get {
                return ResourceManager.GetString("StockIDIsNullMessage", resourceCulture);
            }
        }
        public static string CancelCompleteExistsInvoice
        {
            get
            {
                return ResourceManager.GetString("CancelCompleteExistsInvoice", resourceCulture);
            }
        }
    }
}
