using BOSLib;
using System.Collections.Generic;
using System.Data;


namespace BOSERP
{
    #region ACEInvoiceDetails
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ACEInvoiceDetailsController
    //Created Date:Saturday, January 19, 2019
    //-----------------------------------------------------------

    public class ACEInvoiceDetailsController : BaseBusinessController
    {
        public ACEInvoiceDetailsController()
        {
            dal = new DALBaseProvider("ACEInvoiceDetails", typeof(ACEInvoiceDetailsInfo));
        }

        public override System.Collections.IList GetListFromDataSet(DataSet ds)
        {
            List<ACEInvoiceDetailsInfo> list = new List<ACEInvoiceDetailsInfo>();
            if (ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    ACEInvoiceDetailsInfo obj = (ACEInvoiceDetailsInfo)GetObjectFromDataRow(row);
                    list.Add(obj);
                }
            }
            ds.Dispose();
            return list;
        }

        public List<ACEInvoiceDetailsInfo> GetInvoiceDetailsByEInvoiceID(int eInvoiceID)
        {
            DataSet ds = dal.GetDataSet("ACEInvoiceDetails_GetInvoiceDetailsByEInvoiceID", eInvoiceID);
            return (List<ACEInvoiceDetailsInfo>)GetListFromDataSet(ds);
        }
    }
    #endregion
}