using BOSLib;
using System.Collections.Generic;
using System.Data;


namespace BOSERP
{
    #region ACListAccountBanks
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ACListAccountBanksController
    //Created Date:07 August 2018
    //-----------------------------------------------------------

    public class ACListAccountBanksController : BaseBusinessController
    {
        public ACListAccountBanksController()
        {
            dal = new DALBaseProvider("ACListAccountBanks", typeof(ACListAccountBanksInfo));
        }

        public override System.Collections.IList GetListFromDataSet(DataSet ds)
        {
            List<ACListAccountBanksInfo> listObjects = new List<ACListAccountBanksInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    ACListAccountBanksInfo item = (ACListAccountBanksInfo)GetObjectFromDataRow(row);
                    listObjects.Add(item);
                }
            }
            ds.Dispose();
            return listObjects;
        }

        public List<ACListAccountBanksInfo> GetListByACObject(int acObjectID, string type)
        {
            DataSet ds = dal.GetDataSet("ACListAccountBanks_GetListByACObjectID", acObjectID, type);
            return (List<ACListAccountBanksInfo>)GetListFromDataSet(ds);
        }

        public DataSet GetListAcctountBanks()
        {
            DataSet ds = dal.GetDataSet("ACListAccountBanks_GetListAcctountBanks");
            return ds;
        }

        public List<ACListAccountBanksInfo> GetAllListAcctountBanks()
        {
            DataSet ds = GetListAcctountBanks();
            return (List<ACListAccountBanksInfo>)GetListFromDataSet(ds);
        }

        public List<ACListAccountBanksInfo> GetAccountBankByObject(int acObjectID, string type)
        {
            DataSet ds = dal.GetDataSet("ACListAccountBanks_GetAccountBankByObject", acObjectID, type);
            return (List<ACListAccountBanksInfo>)GetListFromDataSet(ds);
        }

        public ACListAccountBanksInfo GetAccountBankByIDAndType(int objectID, string type)
        {
            DataSet ds = dal.GetDataSet("ACListAccountBanks_GetAccountBankByObject", objectID, type);
            ACListAccountBanksInfo objObjectsInfo = null;
            if (ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                objObjectsInfo = (ACListAccountBanksInfo)GetObjectFromDataRow(ds.Tables[0].Rows[0]);
            }
            return objObjectsInfo;
        }
    }
    #endregion
}