using BOSLib;


namespace BOSERP
{
    #region ACLoanReceiptInterestRateChanges
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ACLoanReceiptInterestRateChangesController
    //Created Date:Wednesday, July 17, 2019
    //-----------------------------------------------------------

    public class ACLoanReceiptInterestRateChangesController : BaseBusinessController
    {
        public ACLoanReceiptInterestRateChangesController()
        {
            dal = new DALBaseProvider("ACLoanReceiptInterestRateChanges", typeof(ACLoanReceiptInterestRateChangesInfo));
        }
    }
    #endregion
}