using System;
namespace BOSLib
{
    #region STModulePostings
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:STModulePostingsInfo
    //Created Date:18 Tháng Mười Hai 2018
    //-----------------------------------------------------------

    public class STModulePostingsInfo : BusinessObject
    {
        public STModulePostingsInfo()
        {
        }
        #region Variables
        protected int _sTModulePostingID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _STModuleID;
        protected String _sTModulePostingAccountingFunction = String.Empty;
        protected String _sTModulePostingStockFunction = String.Empty;
        protected String _sTModulePostingPurchaseFunction = String.Empty;
        protected String _sTModulePostingAllocationPlanFunction = String.Empty;
        protected String _sTModulePostingSaleOrderFunction = String.Empty;
        protected String _sTModulePostingTransitInFunction = String.Empty;
        protected String _sTModulePostingTransitOutFunction = String.Empty;
        protected String _sTModulePostingInvoiceTransFunction = String.Empty;
        protected String _sTModulePostingInvoiceInTransFunction = String.Empty;
        #endregion

        #region Public properties
        public int STModulePostingID
        {
            get { return _sTModulePostingID; }
            set
            {
                if (value != this._sTModulePostingID)
                {
                    _sTModulePostingID = value;
                    NotifyChanged("STModulePostingID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int STModuleID
        {
            get { return _STModuleID; }
            set
            {
                if (value != this._STModuleID)
                {
                    _STModuleID = value;
                    NotifyChanged("STModuleID");
                }
            }
        }
        public String STModulePostingAccountingFunction
        {
            get { return _sTModulePostingAccountingFunction; }
            set
            {
                if (value != this._sTModulePostingAccountingFunction)
                {
                    _sTModulePostingAccountingFunction = value;
                    NotifyChanged("STModulePostingAccountingFunction");
                }
            }
        }
        public String STModulePostingStockFunction
        {
            get { return _sTModulePostingStockFunction; }
            set
            {
                if (value != this._sTModulePostingStockFunction)
                {
                    _sTModulePostingStockFunction = value;
                    NotifyChanged("STModulePostingStockFunction");
                }
            }
        }
        public String STModulePostingPurchaseFunction
        {
            get { return _sTModulePostingPurchaseFunction; }
            set
            {
                if (value != this._sTModulePostingPurchaseFunction)
                {
                    _sTModulePostingPurchaseFunction = value;
                    NotifyChanged("STModulePostingPurchaseFunction");
                }
            }
        }
        public String STModulePostingAllocationPlanFunction
        {
            get { return _sTModulePostingAllocationPlanFunction; }
            set
            {
                if (value != this._sTModulePostingAllocationPlanFunction)
                {
                    _sTModulePostingAllocationPlanFunction = value;
                    NotifyChanged("STModulePostingAllocationPlanFunction");
                }
            }
        }
        public String STModulePostingSaleOrderFunction
        {
            get { return _sTModulePostingSaleOrderFunction; }
            set
            {
                if (value != this._sTModulePostingSaleOrderFunction)
                {
                    _sTModulePostingSaleOrderFunction = value;
                    NotifyChanged("STModulePostingSaleOrderFunction");
                }
            }
        }
        public String STModulePostingTransitInFunction
        {
            get { return _sTModulePostingTransitInFunction; }
            set
            {
                if (value != this._sTModulePostingTransitInFunction)
                {
                    _sTModulePostingTransitInFunction = value;
                    NotifyChanged("STModulePostingTransitInFunction");
                }
            }
        }
        public String STModulePostingTransitOutFunction
        {
            get { return _sTModulePostingTransitOutFunction; }
            set
            {
                if (value != this._sTModulePostingTransitOutFunction)
                {
                    _sTModulePostingTransitOutFunction = value;
                    NotifyChanged("STModulePostingTransitOutFunction");
                }
            }
        }
        public String STModulePostingInvoiceTransFunction
        {
            get { return _sTModulePostingInvoiceTransFunction; }
            set
            {
                if (value != this._sTModulePostingInvoiceTransFunction)
                {
                    _sTModulePostingInvoiceTransFunction = value;
                    NotifyChanged("STModulePostingInvoiceTransFunction");
                }
            }
        }
        public String STModulePostingInvoiceInTransFunction
        {
            get { return _sTModulePostingInvoiceInTransFunction; }
            set
            {
                if (value != this._sTModulePostingInvoiceInTransFunction)
                {
                    _sTModulePostingInvoiceInTransFunction = value;
                    NotifyChanged("STModulePostingInvoiceInTransFunction");
                }
            }
        }
        #endregion
    }
    #endregion
}