using BOSCommon;
using BOSLib;
using System;
namespace BOSERP
{
    #region APPaymentProposals
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:APPaymentProposalsInfo
    //Created Date:Monday, November 09, 2015
    //-----------------------------------------------------------

    public class APPaymentProposalsInfo : BusinessObject
    {
        public APPaymentProposalsInfo()
        {
        }
        #region Variables
        protected int _aPPaymentProposalID;
        protected string _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected string _aACreatedUser = string.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected string _aAUpdatedUser = string.Empty;
        protected int _fK_HREmployeeID;
        protected int _fK_HRDepartmentID;
        protected int _fK_HRDepartmentRoomID;
        protected int _fK_APSupplierID;
        protected int _fK_APPurchaseOrderID;
        protected int _fK_ICReceiptID;
        protected int _fK_APInvoiceInID;
        protected string _aPPaymentProposalNo = string.Empty;
        protected string _aPPaymentProposalName = string.Empty;
        protected string _aPPaymentProposalDesc = string.Empty;
        protected DateTime _aPPaymentProposalDate = DateTime.MaxValue;
        protected DateTime _aPPaymentProposalPayDate = DateTime.MaxValue;
        protected string _aPPaymentProposalTypeCombo = string.Empty;
        protected string _aPPaymentProposalStatusCombo = string.Empty;
        protected string _aPPriority = string.Empty;
        protected string _aPPaymentProposalPaymentMethodCombo = string.Empty;
        protected string _aPPaymentProposalInvoiceNo = string.Empty;
        protected string _aPPaymentProposalReceiptNo = string.Empty;
        protected string _aPPaymentProposalBookNo = string.Empty;
        protected decimal _aPPaymentProposalRemainAmount;
        protected decimal _aPPaymentProposalPaidAmount;
        protected decimal _aPPaymentProposalTotalAmount;
        protected string _aPPaymentProposalRemark = string.Empty;
        protected string _aPPaymentProposalDocAttachCombo = string.Empty;
        protected int _fK_HREmployeeAccountantID;
        protected int _fK_HREmployeeManagerID;
        protected int _fK_HREmployeeHeadDepartmentID;
        protected DateTime _aPPaymentProposalCheckDate = DateTime.MaxValue;
        protected DateTime _aPPaymentProposalApproveDate = DateTime.MaxValue;
        protected DateTime _aPPaymentProposalConfirmDate = DateTime.MaxValue;
        protected DateTime _aPPaymentProposalApprovePaymentDate = DateTime.MaxValue;
        protected int _fK_HREmployeeHeadAccountantID;
        protected int _fK_ACSegmentID;
        protected string _aPPaymentProposalApproveStatus = Status.NeedApprove.ToString();
        protected int _fK_ACAssObjectID;
        protected string _aPAssObjectType = string.Empty;
        protected string _aPObjectType = string.Empty;
        protected int _fK_ACObjectID;
        protected int _fK_BRBranchID;
        protected int _fK_PMProjectID;
        protected int _fK_GECurrencyID;
        protected int _fK_ACListAccountBankID;
        protected string _aPPaymentProposalReceiverBankName = string.Empty;
        protected string _aPPaymentProposalReceiverBankCode = string.Empty;
        protected string _aPPaymentProposalReceiverAccount = string.Empty;
        protected string _aPPaymentProposalObjectReceiptName = string.Empty;
        protected string _aPPaymentProposalReceiptAddress = string.Empty;
        protected string _aPPaymentProposalProject = String.Empty;
        protected decimal _aPPaymentProposalDiscountPercent;
        protected decimal _aPPaymentProposalDiscountFix;
        protected decimal _aPPaymentProposalTotalPaymentAmount;
        #endregion

        #region Public properties
        public int APPaymentProposalID
        {
            get { return _aPPaymentProposalID; }
            set
            {
                if (value != this._aPPaymentProposalID)
                {
                    _aPPaymentProposalID = value;
                    NotifyChanged("APPaymentProposalID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int FK_HRDepartmentID
        {
            get { return _fK_HRDepartmentID; }
            set
            {
                if (value != this._fK_HRDepartmentID)
                {
                    _fK_HRDepartmentID = value;
                    NotifyChanged("FK_HRDepartmentID");
                }
            }
        }
        public int FK_HRDepartmentRoomID
        {
            get { return _fK_HRDepartmentRoomID; }
            set
            {
                if (value != this._fK_HRDepartmentRoomID)
                {
                    _fK_HRDepartmentRoomID = value;
                    NotifyChanged("FK_HRDepartmentRoomID");
                }
            }
        }
        public int FK_APSupplierID
        {
            get { return _fK_APSupplierID; }
            set
            {
                if (value != this._fK_APSupplierID)
                {
                    _fK_APSupplierID = value;
                    NotifyChanged("FK_APSupplierID");
                }
            }
        }
        public int FK_APPurchaseOrderID
        {
            get { return _fK_APPurchaseOrderID; }
            set
            {
                if (value != this._fK_APPurchaseOrderID)
                {
                    _fK_APPurchaseOrderID = value;
                    NotifyChanged("FK_APPurchaseOrderID");
                }
            }
        }
        public int FK_ICReceiptID
        {
            get { return _fK_ICReceiptID; }
            set
            {
                if (value != this._fK_ICReceiptID)
                {
                    _fK_ICReceiptID = value;
                    NotifyChanged("FK_ICReceiptID");
                }
            }
        }
        public int FK_APInvoiceInID
        {
            get { return _fK_APInvoiceInID; }
            set
            {
                if (value != this._fK_APInvoiceInID)
                {
                    _fK_APInvoiceInID = value;
                    NotifyChanged("FK_APInvoiceInID");
                }
            }
        }
        public String APPaymentProposalNo
        {
            get { return _aPPaymentProposalNo; }
            set
            {
                if (value != this._aPPaymentProposalNo)
                {
                    _aPPaymentProposalNo = value;
                    NotifyChanged("APPaymentProposalNo");
                }
            }
        }
        public String APPaymentProposalName
        {
            get { return _aPPaymentProposalName; }
            set
            {
                if (value != this._aPPaymentProposalName)
                {
                    _aPPaymentProposalName = value;
                    NotifyChanged("APPaymentProposalName");
                }
            }
        }
        public String APPaymentProposalDesc
        {
            get { return _aPPaymentProposalDesc; }
            set
            {
                if (value != this._aPPaymentProposalDesc)
                {
                    _aPPaymentProposalDesc = value;
                    NotifyChanged("APPaymentProposalDesc");
                }
            }
        }
        public DateTime APPaymentProposalDate
        {
            get { return _aPPaymentProposalDate; }
            set
            {
                if (value != this._aPPaymentProposalDate)
                {
                    _aPPaymentProposalDate = value;
                    NotifyChanged("APPaymentProposalDate");
                }
            }
        }
        public DateTime APPaymentProposalPayDate
        {
            get { return _aPPaymentProposalPayDate; }
            set
            {
                if (value != this._aPPaymentProposalPayDate)
                {
                    _aPPaymentProposalPayDate = value;
                    NotifyChanged("APPaymentProposalPayDate");
                }
            }
        }
        public String APPaymentProposalTypeCombo
        {
            get { return _aPPaymentProposalTypeCombo; }
            set
            {
                if (value != this._aPPaymentProposalTypeCombo)
                {
                    _aPPaymentProposalTypeCombo = value;
                    NotifyChanged("APPaymentProposalTypeCombo");
                }
            }
        }
        public String APPaymentProposalStatusCombo
        {
            get { return _aPPaymentProposalStatusCombo; }
            set
            {
                if (value != this._aPPaymentProposalStatusCombo)
                {
                    _aPPaymentProposalStatusCombo = value;
                    NotifyChanged("APPaymentProposalStatusCombo");
                }
            }
        }
        public String APPriority
        {
            get { return _aPPriority; }
            set
            {
                if (value != this._aPPriority)
                {
                    _aPPriority = value;
                    NotifyChanged("APPriority");
                }
            }
        }
        public String APPaymentProposalPaymentMethodCombo
        {
            get { return _aPPaymentProposalPaymentMethodCombo; }
            set
            {
                if (value != this._aPPaymentProposalPaymentMethodCombo)
                {
                    _aPPaymentProposalPaymentMethodCombo = value;
                    NotifyChanged("APPaymentProposalPaymentMethodCombo");
                }
            }
        }
        public String APPaymentProposalInvoiceNo
        {
            get { return _aPPaymentProposalInvoiceNo; }
            set
            {
                if (value != this._aPPaymentProposalInvoiceNo)
                {
                    _aPPaymentProposalInvoiceNo = value;
                    NotifyChanged("APPaymentProposalInvoiceNo");
                }
            }
        }
        public String APPaymentProposalReceiptNo
        {
            get { return _aPPaymentProposalReceiptNo; }
            set
            {
                if (value != this._aPPaymentProposalReceiptNo)
                {
                    _aPPaymentProposalReceiptNo = value;
                    NotifyChanged("APPaymentProposalReceiptNo");
                }
            }
        }
        public String APPaymentProposalBookNo
        {
            get { return _aPPaymentProposalBookNo; }
            set
            {
                if (value != this._aPPaymentProposalBookNo)
                {
                    _aPPaymentProposalBookNo = value;
                    NotifyChanged("APPaymentProposalBookNo");
                }
            }
        }
        public decimal APPaymentProposalRemainAmount
        {
            get { return _aPPaymentProposalRemainAmount; }
            set
            {
                if (value != this._aPPaymentProposalRemainAmount)
                {
                    _aPPaymentProposalRemainAmount = value;
                    NotifyChanged("APPaymentProposalRemainAmount");
                }
            }
        }
        public decimal APPaymentProposalPaidAmount
        {
            get { return _aPPaymentProposalPaidAmount; }
            set
            {
                if (value != this._aPPaymentProposalPaidAmount)
                {
                    _aPPaymentProposalPaidAmount = value;
                    NotifyChanged("APPaymentProposalPaidAmount");
                }
            }
        }
        public decimal APPaymentProposalTotalAmount
        {
            get { return _aPPaymentProposalTotalAmount; }
            set
            {
                if (value != this._aPPaymentProposalTotalAmount)
                {
                    _aPPaymentProposalTotalAmount = value;
                    NotifyChanged("APPaymentProposalTotalAmount");
                }
            }
        }
        public String APPaymentProposalRemark
        {
            get { return _aPPaymentProposalRemark; }
            set
            {
                if (value != this._aPPaymentProposalRemark)
                {
                    _aPPaymentProposalRemark = value;
                    NotifyChanged("APPaymentProposalRemark");
                }
            }
        }
        public String APPaymentProposalDocAttachCombo
        {
            get { return _aPPaymentProposalDocAttachCombo; }
            set
            {
                if (value != this._aPPaymentProposalDocAttachCombo)
                {
                    _aPPaymentProposalDocAttachCombo = value;
                    NotifyChanged("APPaymentProposalDocAttachCombo");
                }
            }
        }
        public int FK_HREmployeeAccountantID
        {
            get { return _fK_HREmployeeAccountantID; }
            set
            {
                if (value != this._fK_HREmployeeAccountantID)
                {
                    _fK_HREmployeeAccountantID = value;
                    NotifyChanged("FK_HREmployeeAccountantID");
                }
            }
        }
        public int FK_HREmployeeManagerID
        {
            get { return _fK_HREmployeeManagerID; }
            set
            {
                if (value != this._fK_HREmployeeManagerID)
                {
                    _fK_HREmployeeManagerID = value;
                    NotifyChanged("FK_HREmployeeManagerID");
                }
            }
        }
        public int FK_HREmployeeHeadDepartmentID
        {
            get { return _fK_HREmployeeHeadDepartmentID; }
            set
            {
                if (value != this._fK_HREmployeeHeadDepartmentID)
                {
                    _fK_HREmployeeHeadDepartmentID = value;
                    NotifyChanged("FK_HREmployeeHeadDepartmentID");
                }
            }
        }
        public DateTime APPaymentProposalCheckDate
        {
            get { return _aPPaymentProposalCheckDate; }
            set
            {
                if (value != this._aPPaymentProposalCheckDate)
                {
                    _aPPaymentProposalCheckDate = value;
                    NotifyChanged("APPaymentProposalCheckDate");
                }
            }
        }
        public DateTime APPaymentProposalApproveDate
        {
            get { return _aPPaymentProposalApproveDate; }
            set
            {
                if (value != this._aPPaymentProposalApproveDate)
                {
                    _aPPaymentProposalApproveDate = value;
                    NotifyChanged("APPaymentProposalApproveDate");
                }
            }
        }
        public DateTime APPaymentProposalConfirmDate
        {
            get { return _aPPaymentProposalConfirmDate; }
            set
            {
                if (value != this._aPPaymentProposalConfirmDate)
                {
                    _aPPaymentProposalConfirmDate = value;
                    NotifyChanged("APPaymentProposalConfirmDate");
                }
            }
        }
        public DateTime APPaymentProposalApprovePaymentDate
        {
            get { return _aPPaymentProposalApprovePaymentDate; }
            set
            {
                if (value != this._aPPaymentProposalApprovePaymentDate)
                {
                    _aPPaymentProposalApprovePaymentDate = value;
                    NotifyChanged("APPaymentProposalApprovePaymentDate");
                }
            }
        }
        public int FK_HREmployeeHeadAccountantID
        {
            get { return _fK_HREmployeeHeadAccountantID; }
            set
            {
                if (value != this._fK_HREmployeeHeadAccountantID)
                {
                    _fK_HREmployeeHeadAccountantID = value;
                    NotifyChanged("FK_HREmployeeHeadAccountantID");
                }
            }
        }
        public int FK_ACSegmentID
        {
            get { return _fK_ACSegmentID; }
            set
            {
                if (value != this._fK_ACSegmentID)
                {
                    _fK_ACSegmentID = value;
                    NotifyChanged("FK_ACSegmentID");
                }
            }
        }
        public String APPaymentProposalApproveStatus
        {
            get { return _aPPaymentProposalApproveStatus; }
            set
            {
                if (value != this._aPPaymentProposalApproveStatus)
                {
                    _aPPaymentProposalApproveStatus = value;
                    NotifyChanged("APPaymentProposalApproveStatus");
                }
            }
        }
        public int FK_ACAssObjectID
        {
            get { return _fK_ACAssObjectID; }
            set
            {
                if (value != this._fK_ACAssObjectID)
                {
                    _fK_ACAssObjectID = value;
                    NotifyChanged("FK_ACAssObjectID");
                }
            }
        }
        public String APAssObjectType
        {
            get { return _aPAssObjectType; }
            set
            {
                if (value != this._aPAssObjectType)
                {
                    _aPAssObjectType = value;
                    NotifyChanged("APAssObjectType");
                }
            }
        }
        public String APObjectType
        {
            get { return _aPObjectType; }
            set
            {
                if (value != this._aPObjectType)
                {
                    _aPObjectType = value;
                    NotifyChanged("APObjectType");
                }
            }
        }
        public int FK_ACObjectID
        {
            get { return _fK_ACObjectID; }
            set
            {
                if (value != this._fK_ACObjectID)
                {
                    _fK_ACObjectID = value;
                    NotifyChanged("FK_ACObjectID");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public int FK_PMProjectID
        {
            get { return _fK_PMProjectID; }
            set
            {
                if (value != this._fK_PMProjectID)
                {
                    _fK_PMProjectID = value;
                    NotifyChanged("FK_PMProjectID");
                }
            }
        }
        public int FK_GECurrencyID
        {
            get { return _fK_GECurrencyID; }
            set
            {
                if (value != this._fK_GECurrencyID)
                {
                    _fK_GECurrencyID = value;
                    NotifyChanged("FK_GECurrencyID");
                }
            }
        }
        public int FK_ACListAccountBankID
        {
            get { return _fK_ACListAccountBankID; }
            set
            {
                if (value != this._fK_ACListAccountBankID)
                {
                    _fK_ACListAccountBankID = value;
                    NotifyChanged("FK_ACListAccountBankID");
                }
            }
        }
        public string APPaymentProposalReceiverBankName
        {
            get { return _aPPaymentProposalReceiverBankName; }
            set
            {
                if (value != this._aPPaymentProposalReceiverBankName)
                {
                    _aPPaymentProposalReceiverBankName = value;
                    NotifyChanged("APPaymentProposalReceiverBankName");
                }
            }
        }
        public string APPaymentProposalReceiverBankCode
        {
            get { return _aPPaymentProposalReceiverBankCode; }
            set
            {
                if (value != this._aPPaymentProposalReceiverBankCode)
                {
                    _aPPaymentProposalReceiverBankCode = value;
                    NotifyChanged("APPaymentProposalReceiverBankCode");
                }
            }
        }
        public string APPaymentProposalReceiverAccount
        {
            get { return _aPPaymentProposalReceiverAccount; }
            set
            {
                if (value != this._aPPaymentProposalReceiverAccount)
                {
                    _aPPaymentProposalReceiverAccount = value;
                    NotifyChanged("APPaymentProposalReceiverAccount");
                }
            }
        }
        public string APPaymentProposalObjectReceiptName
        {
            get { return _aPPaymentProposalObjectReceiptName; }
            set
            {
                if (value != this._aPPaymentProposalObjectReceiptName)
                {
                    _aPPaymentProposalObjectReceiptName = value;
                    NotifyChanged("APPaymentProposalObjectReceiptName");
                }
            }
        }
        public string APPaymentProposalReceiptAddress
        {
            get { return _aPPaymentProposalReceiptAddress; }
            set
            {
                if (value != this._aPPaymentProposalReceiptAddress)
                {
                    _aPPaymentProposalReceiptAddress = value;
                    NotifyChanged("APPaymentProposalReceiptAddress");
                }
            }
        }
        public string APPaymentProposalProject
        {
            get { return _aPPaymentProposalProject; }
            set
            {
                if (value != _aPPaymentProposalProject)
                {
                    _aPPaymentProposalProject = value;
                    NotifyChanged("APPaymentProposalProject");
                }    
            }    
        }
        public decimal APPaymentProposalDiscountPercent
        {
            get { return _aPPaymentProposalDiscountPercent; }
            set
            {
                if (value != this._aPPaymentProposalDiscountPercent)
                {
                    _aPPaymentProposalDiscountPercent = value;
                    NotifyChanged("APPaymentProposalDiscountPercent");
                }
            }
        }
        public decimal APPaymentProposalDiscountFix
        {
            get { return _aPPaymentProposalDiscountFix; }
            set
            {
                if (value != this._aPPaymentProposalDiscountFix)
                {
                    _aPPaymentProposalDiscountFix = value;
                    NotifyChanged("APPaymentProposalDiscountFix");
                }
            }
        }
        public decimal APPaymentProposalTotalPaymentAmount
        {
            get { return _aPPaymentProposalTotalPaymentAmount; }
            set
            {
                if (value != this._aPPaymentProposalTotalPaymentAmount)
                {
                    _aPPaymentProposalTotalPaymentAmount = value;
                    NotifyChanged("APPaymentProposalDiscountFix");
                }
            }
        }
        #endregion

        #region Extra Properties
        public string ACObjectAccessKey { get; set; }
        public DateTime PaymentProposalDateFrom { get; set; }
        public DateTime PaymentProposalDateTo { get; set; }
        public string HRDepartmentRoomName { get; set; }
        public string HREmployeeName { get; set; }
        public string APPaymentProposalTotalAmountWord { get; set; }
        public string APPaymentProposalReference { get; set; }
        public string APPaymentProposalDocAttachDesc { get; set; }
        public string ACAssObjectAccessKey { get; set; }
        public string ACObjectName { get; set; }
        public string APInvoiceInNo { get; set; }
        public string APPurchaseOrderNo { get; set; }
        public string APSupplierPaymentNo { get; set; }
        public string InvoiceInType { get; set; }
        public string APPaymentProposalReason { get; set; }
        public string ACObjectOwing { get; set; }
        public string APPaymentProposalComment { get; set; }
        public long Sort { get; set; }
        public string ICProductTypeGroup { get; set; }
        #endregion Extra Properties
    }
    #endregion
}