UPDATE AAColumnAlias SET AAColumnAliasName = 'ARSaleOrderItemHTText', AAColumnAliasCaption =N'Hoàn Thiện' 
, AAReferenceTable	 = ''
, AADisplayedMember	= ''
,AAFilteredColumn	= ''
,AAFilteredValues = ''
WHERE AATableName = 'ARSaleOrderItems' AND AAColumnAliasName = 'ARSaleOrderItemHTText'