INSERT INTO AAColumnAlias (AANumberInt,AANumberString,AAStatus,AAColumnAliasName,AAColumnAliasCaption,AATableName,AAReferenceTable,AADisplayedMember,AAFilteredColumn,AAFilteredValues,AAAllowDummy,AAColumnAliasIsSaveHistory) SELECT 0,N'',N'Alive',N'SemiProductNo',N'Mã BTP',N'RP_GetMaterialInBOM',N'',N'',N'',N'',1,0
INSERT INTO AAColumnAlias (AANumberInt,AANumberString,AAStatus,AAColumnAliasName,AAColumnAliasCaption,AATableName,AAReferenceTable,AADisplayedMember,AAFilteredColumn,AAFilteredValues,AAAllowDummy,AAColumnAliasIsSaveHistory) SELECT 0,N'',N'Alive',N'SemiProductName',N'Tên BTP',N'RP_GetMaterialInBOM',N'',N'',N'',N'',1,0
INSERT INTO AAColumnAlias (AANumberInt,AANumberString,AAStatus,AAColumnAliasName,AAColumnAliasCaption,AATableName,AAReferenceTable,AADisplayedMember,AAFilteredColumn,AAFilteredValues,AAAllowDummy,AAColumnAliasIsSaveHistory) SELECT 0,N'',N'Alive',N'SemiProductQty',N'SL BTP',N'RP_GetMaterialInBOM',N'',N'',N'',N'',1,0
INSERT INTO AAColumnAlias (AANumberInt,AANumberString,AAStatus,AAColumnAliasName,AAColumnAliasCaption,AATableName,AAReferenceTable,AADisplayedMember,AAFilteredColumn,AAFilteredValues,AAAllowDummy,AAColumnAliasIsSaveHistory) SELECT 0,N'',N'Alive',N'SemiProductLength',N'Dài BTP',N'RP_GetMaterialInBOM',N'',N'',N'',N'',1,0
INSERT INTO AAColumnAlias (AANumberInt,AANumberString,AAStatus,AAColumnAliasName,AAColumnAliasCaption,AATableName,AAReferenceTable,AADisplayedMember,AAFilteredColumn,AAFilteredValues,AAAllowDummy,AAColumnAliasIsSaveHistory) SELECT 0,N'',N'Alive',N'SemiProductWidth',N'Rộng BTP',N'RP_GetMaterialInBOM',N'',N'',N'',N'',1,0
INSERT INTO AAColumnAlias (AANumberInt,AANumberString,AAStatus,AAColumnAliasName,AAColumnAliasCaption,AATableName,AAReferenceTable,AADisplayedMember,AAFilteredColumn,AAFilteredValues,AAAllowDummy,AAColumnAliasIsSaveHistory) SELECT 0,N'',N'Alive',N'SemiProductHeight',N'Dày BTP',N'RP_GetMaterialInBOM',N'',N'',N'',N'',1,0

INSERT INTO STFieldFormats (STFieldFormatModuleName,STFieldFormatTableName,STFieldFormatGroupID,STFieldFormatColumnName,STChangeByCurrency,STChangeByDepartment) SELECT N'Report',N'RP_GetMaterialInBOM',8,N'SemiProductQty',0,0
INSERT INTO STFieldFormats (STFieldFormatModuleName,STFieldFormatTableName,STFieldFormatGroupID,STFieldFormatColumnName,STChangeByCurrency,STChangeByDepartment) SELECT N'Report',N'RP_GetMaterialInBOM',8,N'SemiProductLength',0,0
INSERT INTO STFieldFormats (STFieldFormatModuleName,STFieldFormatTableName,STFieldFormatGroupID,STFieldFormatColumnName,STChangeByCurrency,STChangeByDepartment) SELECT N'Report',N'RP_GetMaterialInBOM',8,N'SemiProductWidth',0,0
INSERT INTO STFieldFormats (STFieldFormatModuleName,STFieldFormatTableName,STFieldFormatGroupID,STFieldFormatColumnName,STChangeByCurrency,STChangeByDepartment) SELECT N'Report',N'RP_GetMaterialInBOM',8,N'SemiProductHeight',0,0