Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICShipmentItemSOName', N'Tên DHNB', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'MMBatchProductNo', N'Lệnh sản xuất', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICShipmentItemProductNo', N'Mã gỗ xuất', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICProductNo', N'Mã sản phẩm', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICProductName', N'Tên sản phẩm', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICMeasureUnitName', N'Đơn vị tính', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICShipmentItemProductHeight', N'Dày(mm)', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICShipmentItemProductWidth', N'Rộng(mm)', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICShipmentItemProductLength', N'Dài(mm)', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICShipmentItemQty1', N'Số thanh(tấm)', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICShipmentItemProductQty', N'Khối lượng', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICShipmentItemProductUnitPrice', N'Đơn giá', N'IPShipmentItems', '', '', '', '', 1, 0)
Insert into AAColumnAlias Values ('0', '', 'Alive', 'ICImportAndExportReasonName', N'Lý do nhập xuất kho', N'IPShipmentItems', '', '', '', '', 1, 0)

insert into STFieldFormats Values ('MaterialShipment', 'IPShipmentItems', (Select STFieldFormatGroupID from STFieldFormatGroups Where STFieldFormatGroupName = 'FormatGroupN3'), 'ICShipmentItemProductHeight', 0,0)
insert into STFieldFormats Values ('MaterialShipment', 'IPShipmentItems', (Select STFieldFormatGroupID from STFieldFormatGroups Where STFieldFormatGroupName = 'FormatGroupN3'), 'ICShipmentItemProductWidth', 0,0)
insert into STFieldFormats Values ('MaterialShipment', 'IPShipmentItems', (Select STFieldFormatGroupID from STFieldFormatGroups Where STFieldFormatGroupName = 'FormatGroupN3'), 'ICShipmentItemProductLength', 0,0)
insert into STFieldFormats Values ('MaterialShipment', 'IPShipmentItems', (Select STFieldFormatGroupID from STFieldFormatGroups Where STFieldFormatGroupName = 'FormatGroupN3'), 'ICShipmentItemQty1', 0,0)
insert into STFieldFormats Values ('MaterialShipment', 'IPShipmentItems', (Select STFieldFormatGroupID from STFieldFormatGroups Where STFieldFormatGroupName = 'FormatGroupN6'), 'ICShipmentItemProductQty', 0,0)
insert into STFieldFormats Values ('MaterialShipment', 'IPShipmentItems', (Select STFieldFormatGroupID from STFieldFormatGroups Where STFieldFormatGroupName = 'FormatGroupPriceByCurrency'), 'ICShipmentItemProductUnitPrice', 0,0)
