using BOSLib;
using System;
namespace BOSERP
{
    #region HREmployeeGroups
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HREmployeeGroupsInfo
    //Created Date:25 Tháng Sáu 2018
    //-----------------------------------------------------------

    public class HREmployeeGroupsInfo : BusinessObject
    {
        public HREmployeeGroupsInfo()
        {
        }
        #region Variables
        protected int _hREmployeeGroupID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_HREmployeeID;
        protected int _fK_HRGroupID;
        protected int _fK_BRBranchID;
        protected bool _isLeader = false;
        protected String _hREmployeeGroupCRMRole = String.Empty;
        #endregion

        #region Public properties
        public int HREmployeeGroupID
        {
            get { return _hREmployeeGroupID; }
            set
            {
                if (value != this._hREmployeeGroupID)
                {
                    _hREmployeeGroupID = value;
                    NotifyChanged("HREmployeeGroupID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int FK_HRGroupID
        {
            get { return _fK_HRGroupID; }
            set
            {
                if (value != this._fK_HRGroupID)
                {
                    _fK_HRGroupID = value;
                    NotifyChanged("FK_HRGroupID");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public bool IsLeader
        {
            get { return _isLeader; }
            set
            {
                if (value != this._isLeader)
                {
                    _isLeader = value;
                    NotifyChanged("IsLeader");
                }
            }
        }
        public String HREmployeeGroupCRMRole
        {
            get { return _hREmployeeGroupCRMRole; }
            set
            {
                if (value != this._hREmployeeGroupCRMRole)
                {
                    _hREmployeeGroupCRMRole = value;
                    NotifyChanged("HREmployeeGroupCRMRole");
                }
            }
        }
        #endregion
    }
    #endregion
}