using BOSLib;
using System;
namespace BOSERP
{
    #region HRSocialInsuranceDeclarations
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HRSocialInsuranceDeclarationsInfo
    //Created Date:Tuesday, December 24, 2019
    //-----------------------------------------------------------

    public class HRSocialInsuranceDeclarationsInfo : BusinessObject
    {
        public HRSocialInsuranceDeclarationsInfo()
        {
        }
        #region Variables
        protected int _hRSocialInsuranceDeclarationID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected int _fK_HREmployeeID;
        protected int _fK_BRBranchID;
        protected String _hRSocialInsuranceDeclarationNo = String.Empty;
        protected String _hRSocialInsuranceDeclarationName = String.Empty;
        protected String _hRSocialInsuranceDeclarationDesc = String.Empty;
        protected DateTime _hRSocialInsuranceDeclarationDate = DateTime.MaxValue;
        protected String _hRSocialInsuranceDeclarationStatus = DefaultStatus;
        protected String _hRSocialInsuranceDeclarationType = String.Empty;
        #endregion

        #region Public properties
        public int HRSocialInsuranceDeclarationID
        {
            get { return _hRSocialInsuranceDeclarationID; }
            set
            {
                if (value != this._hRSocialInsuranceDeclarationID)
                {
                    _hRSocialInsuranceDeclarationID = value;
                    NotifyChanged("HRSocialInsuranceDeclarationID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public String HRSocialInsuranceDeclarationNo
        {
            get { return _hRSocialInsuranceDeclarationNo; }
            set
            {
                if (value != this._hRSocialInsuranceDeclarationNo)
                {
                    _hRSocialInsuranceDeclarationNo = value;
                    NotifyChanged("HRSocialInsuranceDeclarationNo");
                }
            }
        }
        public String HRSocialInsuranceDeclarationName
        {
            get { return _hRSocialInsuranceDeclarationName; }
            set
            {
                if (value != this._hRSocialInsuranceDeclarationName)
                {
                    _hRSocialInsuranceDeclarationName = value;
                    NotifyChanged("HRSocialInsuranceDeclarationName");
                }
            }
        }
        public String HRSocialInsuranceDeclarationDesc
        {
            get { return _hRSocialInsuranceDeclarationDesc; }
            set
            {
                if (value != this._hRSocialInsuranceDeclarationDesc)
                {
                    _hRSocialInsuranceDeclarationDesc = value;
                    NotifyChanged("HRSocialInsuranceDeclarationDesc");
                }
            }
        }
        public DateTime HRSocialInsuranceDeclarationDate
        {
            get { return _hRSocialInsuranceDeclarationDate; }
            set
            {
                if (value != this._hRSocialInsuranceDeclarationDate)
                {
                    _hRSocialInsuranceDeclarationDate = value;
                    NotifyChanged("HRSocialInsuranceDeclarationDate");
                }
            }
        }
        public String HRSocialInsuranceDeclarationStatus
        {
            get { return _hRSocialInsuranceDeclarationStatus; }
            set
            {
                if (value != this._hRSocialInsuranceDeclarationStatus)
                {
                    _hRSocialInsuranceDeclarationStatus = value;
                    NotifyChanged("HRSocialInsuranceDeclarationStatus");
                }
            }
        }
        public String HRSocialInsuranceDeclarationType
        {
            get { return _hRSocialInsuranceDeclarationType; }
            set
            {
                if (value != this._hRSocialInsuranceDeclarationType)
                {
                    _hRSocialInsuranceDeclarationType = value;
                    NotifyChanged("HRSocialInsuranceDeclarationType");
                }
            }
        }
        #endregion

        #region Extra
        public byte[] HRSocialInsuranceDeclarationEmployeePicture { get; set; }
        /// <summary>
        /// Gets or sets the time sheets of employees
        /// </summary>
        public DateTime HRSocialInsuranceDeclarationDateFrom { get; set; }
        public DateTime HRSocialInsuranceDeclarationDateTo { get; set; }
        #endregion
    }
    #endregion
}