using BOSLib;
using System.Collections.Generic;
using System.Data;


namespace BOSERP
{
    #region GEStockNumberings
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:GEStockNumberingsController
    //Created Date:17 Tháng Giêng 2018
    //-----------------------------------------------------------

    public class GEStockNumberingsController : BaseBusinessController
    {
        public GEStockNumberingsController()
        {
            dal = new DALBaseProvider("GEStockNumberings", typeof(GEStockNumberingsInfo));
        }

        public GEStockNumberingsInfo GetGEStockNumberingByModuleNameAndStockID(string moduleName, int stockID)
        {
            List<GEStockNumberingsInfo> stockNumberingList = new List<GEStockNumberingsInfo>();
            DataSet ds = dal.GetDataSet("GEStockNumberings_GetStockNumberingsListByModuleNameAndStockID", moduleName, stockID);
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    GEStockNumberingsInfo objStockNumberingsInfo = (GEStockNumberingsInfo)GetObjectFromDataRow(row);
                    stockNumberingList.Add(objStockNumberingsInfo);
                }
            }

            if (stockNumberingList.Count > 0)
                return stockNumberingList[0];

            return null;
        }
        public List<GEStockNumberingsInfo> GetAllObject()
        {
            List<GEStockNumberingsInfo> stockNumberingList = new List<GEStockNumberingsInfo>();
            DataSet ds = dal.GetAllObject();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    GEStockNumberingsInfo objStockNumberingsInfo = (GEStockNumberingsInfo)GetObjectFromDataRow(row);
                    stockNumberingList.Add(objStockNumberingsInfo);
                }
            }
            return stockNumberingList;
        }
    }
    #endregion
}