using BOSLib;
using System;
using System.Collections.Generic;
using System.Data;


namespace BOSERP
{
    #region HRBonusSaleItems
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HRBonusSaleItemsController
    //Created Date:Thursday, February 14, 2019
    //-----------------------------------------------------------

    public class HRBonusSaleItemsController : BaseBusinessController
    {
        public HRBonusSaleItemsController()
        {
            dal = new DALBaseProvider("HRBonusSaleItems", typeof(HRBonusSaleItemsInfo));
        }

        public override System.Collections.IList GetListFromDataSet(DataSet ds)
        {
            List<HRBonusSaleItemsInfo> bonusSaleItems = new List<HRBonusSaleItemsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRBonusSaleItemsInfo objBonusSaleItemsInfo = (HRBonusSaleItemsInfo)GetObjectFromDataRow(row);
                    bonusSaleItems.Add(objBonusSaleItemsInfo);
                }
            }
            ds.Dispose();
            return bonusSaleItems;
        }

        public List<HRBonusSaleItemsInfo> GetBonusSaleItemsForConfigSalesPayroll(DateTime dateFrom, DateTime dateTo)
        {
            return (List<HRBonusSaleItemsInfo>)GetListFromDataSet(dal.GetDataSet("HRBonusSaleItems_GetBonusSaleItemsForConfigSalesPayroll", dateFrom, dateTo));
        }
    }
    #endregion
}