using BOSLib;
using System.Collections.Generic;
using System.Data;


namespace BOSERP
{
    #region HRCostTypeConfigs
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HRCostTypeConfigsController
    //Created Date:Wednesday, May 29, 2019
    //-----------------------------------------------------------

    public class HRCostTypeConfigsController : BaseBusinessController
    {
        public HRCostTypeConfigsController()
        {
            dal = new DALBaseProvider("HRCostTypeConfigs", typeof(HRCostTypeConfigsInfo));
        }

        public override System.Collections.IList GetListFromDataSet(DataSet ds)
        {
            List<HRCostTypeConfigsInfo> entries = new List<HRCostTypeConfigsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRCostTypeConfigsInfo entry = (HRCostTypeConfigsInfo)GetObjectFromDataRow(row);
                    entries.Add(entry);
                }
            }
            ds.Dispose();
            return entries;
        }
    }
    #endregion
}