using BOSLib;
using System.Collections.Generic;
using System.Data;


namespace BOSERP
{
    #region MMConfigAccountOperations
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MMConfigAccountOperationsController
    //Created Date:Friday, March 22, 2019
    //-----------------------------------------------------------

    public class MMConfigAccountOperationsController : BaseBusinessController
    {
        public MMConfigAccountOperationsController()
        {
            dal = new DALBaseProvider("MMConfigAccountOperations", typeof(MMConfigAccountOperationsInfo));
        }
        public override System.Collections.IList GetListFromDataSet(DataSet ds)
        {
            List<MMConfigAccountOperationsInfo> products = new List<MMConfigAccountOperationsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    MMConfigAccountOperationsInfo objProductsInfo = (MMConfigAccountOperationsInfo)GetObjectFromDataRow(row);
                    products.Add(objProductsInfo);
                }
            }
            ds.Dispose();
            return products;
        }
        public MMConfigAccountOperationsInfo GetItemByOperationIDAndDepartmentID(int operationID, int departmentID)
        {
            DataSet ds = dal.GetDataSet("MMConfigAccountOperations_GetItemByOperationIDAndDepartmentID", operationID, departmentID);
            if (ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                MMConfigAccountOperationsInfo objOperationsInfo = (MMConfigAccountOperationsInfo)GetObjectFromDataRow(ds.Tables[0].Rows[0]);
                ds.Dispose();
                return objOperationsInfo;
            }
            return null;
        }
    }
    #endregion
}