using BOSLib;


namespace BOSERP
{
    #region MMNormTemplateProducts
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MMNormTemplateProductsController
    //Created Date:Tuesday, November 06, 2018
    //-----------------------------------------------------------

    public class MMNormTemplateProductsController : BaseBusinessController
    {
        public MMNormTemplateProductsController()
        {
            dal = new DALBaseProvider("MMNormTemplateProducts", typeof(MMNormTemplateProductsInfo));
        }
    }
    #endregion
}