using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
	#region MMUpdatePositionItems
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:MMUpdatePositionItemsController
	//Created Date:02/01/2024 12:00:00 AM
	//-----------------------------------------------------------

	public class MMUpdatePositionItemsController : BaseBusinessController
	{
		public MMUpdatePositionItemsController()
		{
			dal = new DALBaseProvider("MMUpdatePositionItems", typeof(MMUpdatePositionItemsInfo));
		}

		public override System.Collections.IList GetListFromDataSet(DataSet ds)
		{
			List<MMUpdatePositionItemsInfo> items = new List<MMUpdatePositionItemsInfo>();
			if (ds.Tables.Count > 0)
			{
				foreach (DataRow row in ds.Tables[0].Rows)
				{
					MMUpdatePositionItemsInfo item = (MMUpdatePositionItemsInfo)GetObjectFromDataRow(row);
					items.Add(item);
				}
			}
			return items;
		}
		public MMUpdatePositionItemsInfo GetItemByLocationName(string updatePositionItemLocationName, int? productID, int? stockID, int? serieID)
		{
			DataSet ds = dal.GetDataSet("MMUpdatePositionItems_GetItemByLocationName", updatePositionItemLocationName, productID, stockID, serieID);
			if (ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
			{
				MMUpdatePositionItemsInfo objUpdatePositionItemsInfo = (MMUpdatePositionItemsInfo)GetObjectFromDataRow(ds.Tables[0].Rows[0]);
				ds.Dispose();
				return objUpdatePositionItemsInfo;
			}
			return null;
		}
		public List<MMUpdatePositionItemsInfo> GetAllLocationNameByProduct(int? productID, int? stockID, int? serieID)
		{
			DataSet ds = dal.GetDataSet("MMUpdatePositionItems_GetAllLocationNameByProduct", productID, stockID, serieID);
			return (List<MMUpdatePositionItemsInfo>)GetListFromDataSet(ds);
		}
		public List<MMUpdatePositionItemsInfo> GetAllLocationName()
		{
			DataSet ds = dal.GetDataSet("MMUpdatePositionItems_GetAllLocationName");
			return (List<MMUpdatePositionItemsInfo>)GetListFromDataSet(ds);
		}
	}
	#endregion
}