using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
	#region ICCalculatedPackageVolumnConfigs
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:ICCalculatedPackageVolumnConfigsInfo
	//Created Date:13/01/2022 07:59:21
	//-----------------------------------------------------------

	public class ICCalculatedPackageVolumnConfigsInfo : BusinessObject
	{
		public ICCalculatedPackageVolumnConfigsInfo()
		{
		}
		#region Variables
		protected int _iCCalculatedPackageVolumnConfigID;
		protected string _aAStatus = DefaultAAStatus;
		protected DateTime _aACreatedDate = DateTime.MaxValue;
		protected string _aACreatedUser = string.Empty;
		protected DateTime _aAUpdatedDate = DateTime.MaxValue;
		protected string _aAUpdatedUser = string.Empty;
		protected int _sTModuleID;
		protected bool _isActive = true;
		#endregion

		#region Public properties
		public int ICCalculatedPackageVolumnConfigID
		{
			get { return _iCCalculatedPackageVolumnConfigID; }
			set
			{
				if (value != this._iCCalculatedPackageVolumnConfigID)
				{
					_iCCalculatedPackageVolumnConfigID = value;
					NotifyChanged("ICCalculatedPackageVolumnConfigID");
				}
			}
		}
		public string AAStatus
		{
			get { return _aAStatus; }
			set
			{
				if (value != this._aAStatus)
				{
					_aAStatus = value;
					NotifyChanged("AAStatus");
				}
			}
		}
		public DateTime AACreatedDate
		{
			get { return _aACreatedDate; }
			set
			{
				if (value != this._aACreatedDate)
				{
					_aACreatedDate = value;
					NotifyChanged("AACreatedDate");
				}
			}
		}
		public string AACreatedUser
		{
			get { return _aACreatedUser; }
			set
			{
				if (value != this._aACreatedUser)
				{
					_aACreatedUser = value;
					NotifyChanged("AACreatedUser");
				}
			}
		}
		public DateTime AAUpdatedDate
		{
			get { return _aAUpdatedDate; }
			set
			{
				if (value != this._aAUpdatedDate)
				{
					_aAUpdatedDate = value;
					NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public string AAUpdatedUser
		{
			get { return _aAUpdatedUser; }
			set
			{
				if (value != this._aAUpdatedUser)
				{
					_aAUpdatedUser = value;
					NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public int STModuleID
		{
			get { return _sTModuleID; }
			set
			{
				if (value != this._sTModuleID)
				{
					_sTModuleID = value;
					NotifyChanged("STModuleID");
				}
			}
		}
		public bool IsActive
		{
			get { return _isActive; }
			set
			{
				if (value != this._isActive)
				{
					_isActive = value;
					NotifyChanged("IsActive");
				}
			}
		}
		#endregion

		#region Extra properties
		public String STModuleName { get; set; }
		#endregion
	}
    #endregion
}