using BOSLib;
using System;
namespace BOSERP
{
    #region ICProductOperations
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ICProductOperationsInfo
    //Created Date:Friday, October 04, 2019
    //-----------------------------------------------------------

    public class ICProductOperationsInfo : BusinessObject
    {
        public ICProductOperationsInfo()
        {
        }
        #region Variables
        protected int _iCProductOperationID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected int _fK_ICProductID;
        protected int _fK_MMOperationID;
        protected String _iCProductOperationNo = String.Empty;
        protected String _iCProductOperationName = String.Empty;
        protected String _iCProductOperationDesc = String.Empty;
        protected decimal _iCProductOperationSetupTime;
        protected decimal _iCProductOperationCapacity;
        protected String _iCCapacityUnit = String.Empty;
        #endregion

        #region Public properties
        public int ICProductOperationID
        {
            get { return _iCProductOperationID; }
            set
            {
                if (value != this._iCProductOperationID)
                {
                    _iCProductOperationID = value;
                    NotifyChanged("ICProductOperationID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_MMOperationID
        {
            get { return _fK_MMOperationID; }
            set
            {
                if (value != this._fK_MMOperationID)
                {
                    _fK_MMOperationID = value;
                    NotifyChanged("FK_MMOperationID");
                }
            }
        }
        public String ICProductOperationNo
        {
            get { return _iCProductOperationNo; }
            set
            {
                if (value != this._iCProductOperationNo)
                {
                    _iCProductOperationNo = value;
                    NotifyChanged("ICProductOperationNo");
                }
            }
        }
        public String ICProductOperationName
        {
            get { return _iCProductOperationName; }
            set
            {
                if (value != this._iCProductOperationName)
                {
                    _iCProductOperationName = value;
                    NotifyChanged("ICProductOperationName");
                }
            }
        }
        public String ICProductOperationDesc
        {
            get { return _iCProductOperationDesc; }
            set
            {
                if (value != this._iCProductOperationDesc)
                {
                    _iCProductOperationDesc = value;
                    NotifyChanged("ICProductOperationDesc");
                }
            }
        }
        public decimal ICProductOperationSetupTime
        {
            get { return _iCProductOperationSetupTime; }
            set
            {
                if (value != this._iCProductOperationSetupTime)
                {
                    _iCProductOperationSetupTime = value;
                    NotifyChanged("ICProductOperationSetupTime");
                }
            }
        }
        public decimal ICProductOperationCapacity
        {
            get { return _iCProductOperationCapacity; }
            set
            {
                if (value != this._iCProductOperationCapacity)
                {
                    _iCProductOperationCapacity = value;
                    NotifyChanged("ICProductOperationCapacity");
                }
            }
        }
        public String ICCapacityUnit
        {
            get { return _iCCapacityUnit; }
            set
            {
                if (value != this._iCCapacityUnit)
                {
                    _iCCapacityUnit = value;
                    NotifyChanged("ICCapacityUnit");
                }
            }
        }
        #endregion

    }
    #endregion
}