using BOSLib;
using System;
namespace BOSERP
{
    #region ICProductItemMaterials
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ICProductItemMaterialsInfo
    //Created Date:Friday, January 04, 2019
    //-----------------------------------------------------------

    public class ICProductItemMaterialsInfo : BusinessObject
    {
        public ICProductItemMaterialsInfo()
        {
            ICProductItemMaterialDepreciationRate = 1;
        }
        #region Variables
        protected int _iCProductItemMaterialID;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ICProductCarcassID;
        protected int _fK_ICProductID;
        protected int _fK_ICProductMaterialID;
        protected decimal _iCProductItemMaterialLength;
        protected decimal _iCProductItemMaterialWidth;
        protected decimal _iCProductItemMaterialHeigth;
        protected decimal _iCProductItemMaterialQty;
        protected decimal _iCProductItemMaterialWoodQty;
        protected decimal _iCProductItemMaterialDepreciationRate;
        protected decimal _iCProductItemMaterialDepreciationQty;
        protected int _fK_ICMeasureUnitID;
        protected int _fK_MMFormulaID;
        protected int _fK_MMOperationID;
        protected int _fK_MMProductionNormID;
        protected int _fK_ICProductDetailID;
        protected bool _iCProductItemMaterialIsGrain = false;
        #endregion

        #region Public properties
        public int ICProductItemMaterialID
        {
            get { return _iCProductItemMaterialID; }
            set
            {
                if (value != this._iCProductItemMaterialID)
                {
                    _iCProductItemMaterialID = value;
                    NotifyChanged("ICProductItemMaterialID");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_ICProductCarcassID
        {
            get { return _fK_ICProductCarcassID; }
            set
            {
                if (value != this._fK_ICProductCarcassID)
                {
                    _fK_ICProductCarcassID = value;
                    NotifyChanged("FK_ICProductCarcassID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICProductMaterialID
        {
            get { return _fK_ICProductMaterialID; }
            set
            {
                if (value != this._fK_ICProductMaterialID)
                {
                    _fK_ICProductMaterialID = value;
                    NotifyChanged("FK_ICProductMaterialID");
                }
            }
        }
        public decimal ICProductItemMaterialLength
        {
            get { return _iCProductItemMaterialLength; }
            set
            {
                if (value != this._iCProductItemMaterialLength)
                {
                    _iCProductItemMaterialLength = value;
                    NotifyChanged("ICProductItemMaterialLength");
                }
            }
        }
        public decimal ICProductItemMaterialWidth
        {
            get { return _iCProductItemMaterialWidth; }
            set
            {
                if (value != this._iCProductItemMaterialWidth)
                {
                    _iCProductItemMaterialWidth = value;
                    NotifyChanged("ICProductItemMaterialWidth");
                }
            }
        }
        public decimal ICProductItemMaterialHeigth
        {
            get { return _iCProductItemMaterialHeigth; }
            set
            {
                if (value != this._iCProductItemMaterialHeigth)
                {
                    _iCProductItemMaterialHeigth = value;
                    NotifyChanged("ICProductItemMaterialHeigth");
                }
            }
        }
        public decimal ICProductItemMaterialQty
        {
            get { return _iCProductItemMaterialQty; }
            set
            {
                if (value != this._iCProductItemMaterialQty)
                {
                    _iCProductItemMaterialQty = value;
                    NotifyChanged("ICProductItemMaterialQty");
                }
            }
        }
        public decimal ICProductItemMaterialWoodQty
        {
            get { return _iCProductItemMaterialWoodQty; }
            set
            {
                if (value != this._iCProductItemMaterialWoodQty)
                {
                    _iCProductItemMaterialWoodQty = value;
                    NotifyChanged("ICProductItemMaterialWoodQty");
                }
            }
        }
        public decimal ICProductItemMaterialDepreciationRate
        {
            get { return _iCProductItemMaterialDepreciationRate; }
            set
            {
                if (value != this._iCProductItemMaterialDepreciationRate)
                {
                    _iCProductItemMaterialDepreciationRate = value;
                    NotifyChanged("ICProductItemMaterialDepreciationRate");
                }
            }
        }
        public decimal ICProductItemMaterialDepreciationQty
        {
            get { return _iCProductItemMaterialDepreciationQty; }
            set
            {
                if (value != this._iCProductItemMaterialDepreciationQty)
                {
                    _iCProductItemMaterialDepreciationQty = value;
                    NotifyChanged("ICProductItemMaterialDepreciationQty");
                }
            }
        }
        public int FK_ICMeasureUnitID
        {
            get { return _fK_ICMeasureUnitID; }
            set
            {
                if (value != this._fK_ICMeasureUnitID)
                {
                    _fK_ICMeasureUnitID = value;
                    NotifyChanged("FK_ICMeasureUnitID");
                }
            }
        }
        public int FK_MMFormulaID
        {
            get { return _fK_MMFormulaID; }
            set
            {
                if (value != this._fK_MMFormulaID)
                {
                    _fK_MMFormulaID = value;
                    NotifyChanged("FK_MMFormulaID");
                }
            }
        }
        public int FK_MMOperationID
        {
            get { return _fK_MMOperationID; }
            set
            {
                if (value != this._fK_MMOperationID)
                {
                    _fK_MMOperationID = value;
                    NotifyChanged("FK_MMOperationID");
                }
            }
        }
        public int FK_MMProductionNormID
        {
            get { return _fK_MMProductionNormID; }
            set
            {
                if (value != this._fK_MMProductionNormID)
                {
                    _fK_MMProductionNormID = value;
                    NotifyChanged("FK_MMProductionNormID");
                }
            }
        }
        public int FK_ICProductDetailID
        {
            get { return _fK_ICProductDetailID; }
            set
            {
                if (value != this._fK_ICProductDetailID)
                {
                    _fK_ICProductDetailID = value;
                    NotifyChanged("FK_ICProductDetailID");
                }
            }
        }
        public bool ICProductItemMaterialIsGrain
        {
            get { return _iCProductItemMaterialIsGrain; }
            set
            {
                if (value != this._iCProductItemMaterialIsGrain)
                {
                    _iCProductItemMaterialIsGrain = value;
                    NotifyChanged("ICProductItemMaterialIsGrain");
                }
            }
        }
        #endregion


        #region Extra properties
        public string ICMeasureUnitName { get; set; }
        public string ICProductNo { get; set; }
        public string ICProductName { get; set; }
        public string ICProductDetailProductName { get; set; }
        public decimal KLTinh { get; set; }
        public string IPProductionItemParentCode { get; set; }
        public int FK_MMOperationProcessID { get; set; }
        public int FK_ICProductAttributeWoodTypeID { get; set; }
        public string MMOperationMaterialName { get; set; }
        public decimal MMProductionNormItemProductHeight { get; set; }
        public decimal MMProductionNormItemProductLength { get; set; }
        public decimal MMProductionNormItemProductWidth { get; set; }
        #endregion
    }
    #endregion
}